// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. All rights reserved, subject to their exceptions.

/** Public brand/product sites for descriptive icon sourcing, not endorsements. */
export const BRAND_SITES: Record<string, string> = {
  "Capital One": "https://www.capitalone.com/", "Chase": "https://www.chase.com/",
  "Bank of America": "https://www.bankofamerica.com/", "Wells Fargo": "https://www.wellsfargo.com/",
  "Citi": "https://www.citi.com/", "American Express": "https://www.americanexpress.com/",
  "U.S. Bank": "https://www.usbank.com/", "SoFi": "https://www.sofi.com/", "Chime": "https://www.chime.com/",
  "Fifth Third": "https://www.53.com/", "中国农业银行": "https://www.abchina.com/",
  "中国工商银行": "https://www.icbc.com.cn/", "中国建设银行": "https://www.ccb.com/",
  "中国银行": "https://www.boc.cn/", "招商银行／掌上生活": "https://www.cmbchina.com/",
  "交通银行／买单吧": "https://www.bankcomm.com/", "邮储银行": "https://www.psbc.com/",
  "平安口袋银行": "https://bank.pingan.com/", "中信银行／动卡空间": "https://www.citicbank.com/",
  "兴业银行": "https://www.cib.com.cn/", "浦发银行／浦大喜奔": "https://www.spdb.com.cn/",
  "民生银行": "https://www.cmbc.com.cn/", "光大银行": "https://www.cebbank.com/",
  "中银香港／BoC Pay+": "https://www.bochk.com/", "汇丰香港／Reward+": "https://www.hsbc.com.hk/",
  "恒生银行": "https://www.hangseng.com/", "渣打香港": "https://www.sc.com/hk/",
  "Mox": "https://mox.com/", "ZA Bank": "https://bank.za.group/", "DBS Card+ HK": "https://www.dbs.com.hk/",
  "东亚银行": "https://www.hkbea.com/", "建行港澳": "https://www.asia.ccb.com/",
  "Amex Hong Kong": "https://www.americanexpress.com/hk/", "AEON HK": "https://www.aeon.com.hk/",
  "Lloyds": "https://www.lloydsbank.com/", "Monzo": "https://monzo.com/", "NatWest": "https://www.natwest.com/",
  "Nationwide": "https://www.nationwide.co.uk/", "Santander UK": "https://www.santander.co.uk/",
  "Barclays／Barclaycard": "https://www.barclays.co.uk/", "Starling": "https://www.starlingbank.com/",
  "HSBC UK": "https://www.hsbc.co.uk/", "Capital One UK": "https://www.capitalone.co.uk/",
  "Chase UK": "https://www.chase.co.uk/", "Zopa": "https://www.zopa.com/", "Halifax": "https://www.halifax.co.uk/",
  "Amex UK": "https://www.americanexpress.com/en-gb/", "PayPal": "https://www.paypal.com/",
  "Cash App": "https://cash.app/", "Venmo": "https://venmo.com/", "Klarna": "https://www.klarna.com/",
  "Revolut": "https://www.revolut.com/", "Wise": "https://wise.com/", "支付宝": "https://www.alipay.com/",
  "AlipayHK": "https://www.alipayhk.com/", "八达通": "https://www.octopus.com.hk/",
  "云闪付": "https://yunshanfu.unionpay.com/", "PayMe": "https://payme.hsbc.com.hk/",
  "Remitly": "https://www.remitly.com/", "Credit Karma": "https://www.creditkarma.com/",
  "Experian US": "https://www.experian.com/", "Experian UK": "https://www.experian.co.uk/",
  "环联香港": "https://www.transunion.hk/", "ClearScore": "https://www.clearscore.com/",
  "GEICO": "https://www.geico.com/", "Progressive": "https://www.progressive.com/",
  "State Farm": "https://www.statefarm.com/", "AIA HK": "https://www.aia.com.hk/", "AXA HK": "https://www.axa.com.hk/",
  "中国人寿": "https://www.chinalife.com.cn/", "中国人保": "https://www.picc.com/",
  "TradingView": "https://www.tradingview.com/", "富途牛牛": "https://www.futunn.com/", "IBKR": "https://www.interactivebrokers.com/",
  "ChatGPT": "https://chatgpt.com/", "Claude": "https://claude.ai/", "Google Gemini": "https://gemini.google.com/",
  "Grok": "https://grok.com/", "DeepSeek": "https://www.deepseek.com/", "豆包": "https://www.doubao.com/",
  "千问": "https://www.qianwen.com/", "Kimi": "https://www.kimi.com/", "Perplexity": "https://www.perplexity.ai/",
  "Netflix": "https://www.netflix.com/", "Disney+": "https://www.disneyplus.com/", "Prime Video": "https://www.primevideo.com/",
  "HBO Max": "https://www.hbomax.com/", "Hulu": "https://www.hulu.com/", "Peacock": "https://www.peacocktv.com/",
  "Paramount+": "https://www.paramountplus.com/", "腾讯视频": "https://v.qq.com/", "爱奇艺": "https://www.iqiyi.com/",
  "优酷": "https://www.youku.com/", "哔哩哔哩": "https://www.bilibili.com/", "Spotify": "https://www.spotify.com/",
  "YouTube Music": "https://music.youtube.com/", "QQ音乐": "https://y.qq.com/", "网易云音乐": "https://music.163.com/",
  "酷狗音乐": "https://www.kugou.com/", "汽水音乐": "https://music.douyin.com/", "SoundCloud": "https://soundcloud.com/",
  "TIDAL": "https://tidal.com/", "Suno": "https://suno.com/", "Microsoft Teams": "https://teams.microsoft.com/",
  "Zoom": "https://www.zoom.com/", "企业微信": "https://work.weixin.qq.com/", "钉钉": "https://www.dingtalk.com/",
  "飞书": "https://www.feishu.cn/", "Slack": "https://slack.com/", "WPS Office": "https://www.wps.cn/",
  "Notion": "https://www.notion.com/", "Goodnotes": "https://www.goodnotes.com/", "Google Drive": "https://drive.google.com/",
  "Dropbox": "https://www.dropbox.com/", "OneDrive": "https://onedrive.live.com/", "百度网盘": "https://pan.baidu.com/",
  "阿里云盘": "https://www.alipan.com/", "夸克网盘": "https://pan.quark.cn/", "Canva": "https://www.canva.com/",
  "CapCut": "https://www.capcut.com/", "剪映": "https://www.capcut.cn/", "Lightroom": "https://lightroom.adobe.com/",
  "Adobe Express": "https://express.adobe.com/", "Figma": "https://www.figma.com/", "Procreate Pocket": "https://procreate.com/pocket",
  "Strava": "https://www.strava.com/", "AllTrails": "https://www.alltrails.com/", "Keep": "https://www.gotokeep.com/",
  "MyFitnessPal": "https://www.myfitnesspal.com/", "Calm": "https://www.calm.com/", "PureGym": "https://www.puregym.com/",
  "24/7 Fitness": "https://www.247.fitness/", "Planet Fitness": "https://www.planetfitness.com/", "Costco": "https://www.costco.com/",
  "山姆会员商店": "https://www.samsclub.cn/", "Walmart": "https://www.walmart.com/", "京东": "https://www.jd.com/",
  "淘宝": "https://www.taobao.com/", "Tesco": "https://www.tesco.com/", "拼多多": "https://www.pinduoduo.com/",
  "Starbucks": "https://www.starbucks.com/", "瑞幸咖啡": "https://www.lkcoffee.com/", "McDonald's": "https://www.mcdonalds.com/",
  "DoorDash": "https://www.doordash.com/", "Keeta": "https://www.keeta-global.com/", "美团": "https://www.meituan.com/",
  "Uber": "https://www.uber.com/", "Lyft": "https://www.lyft.com/", "Airbnb": "https://www.airbnb.com/",
  "Trip.com": "https://www.trip.com/", "携程": "https://www.ctrip.com/", "滴滴": "https://www.didiglobal.com/",
  "Trainline": "https://www.thetrainline.com/", "MTR Mobile": "https://www.mtr.com.hk/", "Google Maps": "https://maps.google.com/",
  "高德地图": "https://www.amap.com/", "Waze": "https://www.waze.com/", "Citymapper": "https://citymapper.com/",
  "Duolingo": "https://www.duolingo.com/", "Google Classroom": "https://classroom.google.com/", "有道词典": "https://dict.youdao.com/",
  "Google Translate": "https://translate.google.com/", "Kindle": "https://read.amazon.com/", "Audible": "https://www.audible.com/",
  "微信读书": "https://weread.qq.com/", "喜马拉雅": "https://www.ximalaya.com/", "Kobo": "https://www.kobo.com/",
  "The New York Times": "https://www.nytimes.com/", "The Wall Street Journal": "https://www.wsj.com/",
  "The Times": "https://www.thetimes.com/", "The Telegraph": "https://www.telegraph.co.uk/", "South China Morning Post": "https://www.scmp.com/",
  "Substack": "https://substack.com/", "香港01": "https://www.hk01.com/", "微信": "https://weixin.qq.com/",
  "QQ": "https://im.qq.com/", "Telegram": "https://telegram.org/", "Discord": "https://discord.com/", "LinkedIn": "https://www.linkedin.com/",
  "NordVPN": "https://nordvpn.com/", "ExpressVPN": "https://www.expressvpn.com/", "Surfshark": "https://surfshark.com/",
  "中国移动": "https://www.10086.cn/", "中国联通": "https://www.10010.com/", "中国电信": "https://www.189.cn/",
  "GitHub": "https://github.com/", "Replit": "https://replit.com/", "Windy.com": "https://www.windy.com/",
  "AccuWeather": "https://www.accuweather.com/", "彩云天气": "https://caiyunapp.com/", "MyObservatory": "https://www.hko.gov.hk/",
  "CVS Health": "https://www.cvs.com/", "MyChart": "https://www.mychart.org/", "HA Go": "https://www2.ha.org.hk/hago/",
  "NHS App": "https://www.nhs.uk/nhs-app/", "王者荣耀": "https://pvp.qq.com/", "和平精英": "https://gp.qq.com/",
  "RedotPay": "https://www.redotpay.com/", "Bybit Card": "https://www.bybit.com/", "Crypto.com Prepaid Card": "https://crypto.com/",
  "Wirex": "https://wirexapp.com/", "Nexo Card": "https://nexo.com/", "OKX Card": "https://www.okx.com/",
  "Bitget Wallet Card": "https://web3.bitget.com/", "SafePal / Fiat24": "https://www.safepal.com/",
  "TokenPocket TP Card": "https://www.tokenpocket.pro/", "Pionex Card": "https://www.pionex.com/",
  "ether.fi Cash": "https://www.ether.fi/", "MetaMask Card": "https://metamask.io/",
  "中国广电": "https://www.10099.com.cn/", "AT&T": "https://www.att.com/", "Verizon": "https://www.verizon.com/",
  "T-Mobile": "https://www.t-mobile.com/", "Mint Mobile": "https://www.mintmobile.com/", "Metro by T-Mobile": "https://www.metrobyt-mobile.com/",
  "Ultra Mobile": "https://www.ultramobile.com/", "Visible": "https://www.visible.com/", "Total Wireless": "https://www.totalwireless.com/",
  "Cricket Wireless": "https://www.cricketwireless.com/", "Google Fi Wireless": "https://fi.google.com/", "US Mobile": "https://www.usmobile.com/",
  "中国移动香港／CMHK": "https://www.hk.chinamobile.com/", "csl.": "https://www.hkcsl.com/", "1O1O": "https://www.1010.com.hk/",
  "3 Hong Kong": "https://www.three.com.hk/", "SmarTone／数码通": "https://www.smartone.com/", "Birdie／自由鸟": "https://www.birdie.com.hk/",
  "SoSIM": "https://www.sosimhk.com/", "Club SIM": "https://www.clubsim.com.hk/", "SUN Mobile": "https://www.sunmobile.com.hk/",
  "EE": "https://ee.co.uk/", "O2": "https://www.o2.co.uk/", "Vodafone UK": "https://www.vodafone.co.uk/",
  "Three UK": "https://www.three.co.uk/", "giffgaff": "https://www.giffgaff.com/", "Tesco Mobile": "https://www.tescomobile.com/",
  "Sky Mobile": "https://www.sky.com/mobile", "VOXI": "https://www.voxi.co.uk/", "SMARTY": "https://smarty.co.uk/",
  "iD Mobile": "https://www.idmobile.co.uk/", "Lebara UK": "https://www.lebara.co.uk/", "Lycamobile UK": "https://www.lycamobile.co.uk/",
  "Tesla／特斯拉": "https://www.tesla.com/", "Volkswagen／大众": "https://www.volkswagen.com/", "Audi／奥迪": "https://www.audi.com/",
  "Porsche／保时捷": "https://www.porsche.com/", "Škoda／斯柯达": "https://www.skoda-auto.com/", "CUPRA": "https://www.cupraofficial.com/",
  "BMW／宝马": "https://www.bmw.com/", "MINI": "https://www.mini.com/", "Mercedes-Benz／奔驰": "https://www.mercedes-benz.com/",
  "Volvo／沃尔沃": "https://www.volvocars.com/", "Land Rover／路虎": "https://www.landrover.com/", "Jaguar／捷豹": "https://www.jaguar.com/",
  "Peugeot／标致": "https://www.peugeot.com/", "Citroën／雪铁龙": "https://www.citroen.com/", "Vauxhall": "https://www.vauxhall.co.uk/",
  "Renault／雷诺": "https://www.renault.com/", "Fiat／菲亚特": "https://www.fiat.com/", "Jeep": "https://www.jeep.com/",
  "Ford／福特": "https://www.ford.com/", "Lincoln／林肯": "https://www.lincoln.com/", "Chevrolet／雪佛兰": "https://www.chevrolet.com/",
  "Buick／别克": "https://www.buick.com/", "Cadillac／凯迪拉克": "https://www.cadillac.com/", "GMC": "https://www.gmc.com/",
  "Toyota／丰田": "https://www.toyota.com/", "Lexus／雷克萨斯": "https://www.lexus.com/", "Honda／本田": "https://www.honda.com/",
  "Nissan／日产": "https://www.nissan-global.com/", "Mazda／马自达": "https://www.mazda.com/", "Subaru／斯巴鲁": "https://www.subaru.com/",
  "Hyundai／现代": "https://www.hyundai.com/", "Kia／起亚": "https://www.kia.com/", "Genesis／捷尼赛思": "https://www.genesis.com/",
  "BYD／比亚迪": "https://www.byd.com/", "Geely／吉利": "https://www.geely.com/", "Lynk & Co／领克": "https://www.lynkco.com/",
  "Zeekr／极氪": "https://www.zeekrlife.com/", "NIO／蔚来": "https://www.nio.com/", "XPeng／小鹏": "https://www.xiaopeng.com/",
  "理想汽车": "https://www.lixiang.com/", "小米汽车": "https://www.xiaomiev.com/", "AITO／问界": "https://aito.auto/",
  "长安汽车": "https://www.changan.com.cn/", "深蓝汽车": "https://www.deepal.com.cn/", "AVATR／阿维塔": "https://www.avatr.com/",
  "Chery／奇瑞": "https://www.chery.cn/", "HAVAL／哈弗": "https://www.haval.com.cn/", "TANK／坦克": "https://www.tanksuv.com/",
  "AION／埃安": "https://www.aion.com.cn/", "Leapmotor／零跑": "https://www.leapmotor.com/",
  "Apple One": "https://www.apple.com/apple-one/", "iCloud+": "https://www.icloud.com/", "Apple Music": "https://music.apple.com/",
  "Apple TV（订阅服务）": "https://tv.apple.com/", "Apple Arcade": "https://www.apple.com/apple-arcade/",
  "Apple Fitness+": "https://www.apple.com/apple-fitness-plus/", "Apple News+": "https://www.apple.com/apple-news/",
  "Amazon Prime": "https://www.amazon.com/amazonprime", "YouTube Premium": "https://www.youtube.com/premium",
  "Deezer": "https://www.deezer.com/", "DAZN": "https://www.dazn.com/", "NOW（英国）": "https://www.nowtv.com/",
  "Now TV（香港）": "https://www.nowtv.now.com/", "Crunchyroll": "https://www.crunchyroll.com/", "myTV SUPER": "https://www.mytvsuper.com/",
  "Viu": "https://www.viu.com/", "芒果TV": "https://www.mgtv.com/", "Google One": "https://one.google.com/",
  "Microsoft 365": "https://www.microsoft365.com/", "Adobe Creative Cloud": "https://www.adobe.com/creativecloud.html",
  "Todoist": "https://www.todoist.com/", "Setapp": "https://setapp.com/", "1Password": "https://1password.com/",
  "Bitwarden": "https://bitwarden.com/", "Proton": "https://proton.me/", "PlayStation Plus": "https://www.playstation.com/ps-plus/",
  "Xbox Game Pass": "https://www.xbox.com/xbox-game-pass/", "Nintendo Switch Online": "https://www.nintendo.com/us/switch/online/",
  "GeForce NOW": "https://www.nvidia.com/en-us/geforce-now/", "Coursera Plus": "https://www.coursera.org/courseraplus/",
  "MasterClass": "https://www.masterclass.com/", "Skillshare": "https://www.skillshare.com/", "Headspace": "https://www.headspace.com/",
  "Peloton": "https://www.onepeloton.com/", "JetBrains": "https://www.jetbrains.com/", "Cloudflare": "https://www.cloudflare.com/",
  "Vercel": "https://vercel.com/", "DigitalOcean": "https://www.digitalocean.com/", "阿里云": "https://www.aliyun.com/", "腾讯云": "https://cloud.tencent.com/",
}

/** Exact editorial mappings. Never strip Chinese text and accidentally map QQ音乐 to QQ. */
export const SIMPLE_ICON_TITLES: Record<string, string> = {
  "支付宝": "Alipay", "哔哩哔哩": "Bilibili", "网易云音乐": "NetEase Cloud Music",
  "QQ音乐": "QQ Music", "淘宝": "Taobao", "京东": "JD.com", "拼多多": "Pinduoduo",
  "微信": "WeChat", "微软": "Microsoft", "GitHub": "GitHub", "恒生银行": "Hang Seng Bank",
  "汇丰香港／Reward+": "HSBC", "HSBC UK": "HSBC", "Santander UK": "Santander", "Amex Hong Kong": "American Express",
  "Amex UK": "American Express", "Chase UK": "Chase", "Capital One UK": "Capital One", "渣打香港": "Standard Chartered",
  "中国工商银行": "ICBC", "中国银行": "Bank of China", "中国农业银行": "Agricultural Bank of China",
  "T-Mobile": "T-Mobile", "Vodafone UK": "Vodafone", "Google Fi Wireless": "Google Fi",
  "Mercedes-Benz／奔驰": "Mercedes", "Land Rover／路虎": "Land Rover", "Lexus／雷克萨斯": "Lexus",
  "NIO／蔚来": "NIO", "BYD／比亚迪": "BYD", "MetaMask Card": "MetaMask", "Crypto.com Prepaid Card": "Crypto.com",
  "Nexo Card": "Nexo", "OKX Card": "OKX", "Bybit Card": "Bybit", "Wirex": "Wirex", "RedotPay": "RedotPay",
  "Google One": "Google One", "YouTube Premium": "YouTube", "Coursera Plus": "Coursera", "MyObservatory": "Hong Kong Observatory",
}
