// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. All rights reserved, subject to their exceptions.

import { createHash } from "node:crypto"
const input = await Bun.file("docs/brand-catalog/candidate-shortlist-2026-09-08.json").json()
const all = [...input.candidates, ...input.supplements, ...input.sectorCatalog.filter((entry: any) => entry.isAdditionalCandidate)]
if (all.length !== 332 || new Set(all.map(entry => entry.name)).size !== all.length) throw new Error("Invalid catalog")
const ambiguous = new Set(["3", "EE", "NOW", "理想", "坦克", "大众", "Keep", "Calm", "Wise", "Chase", "Chime", "Nationwide", "Starling", "Claude", "Suno", "SUN", "MINI", "csl", "O2"])
const entries = all.map(entry => ({
  id: "brand-" + createHash("sha256").update(entry.name).digest("hex").slice(0, 16),
  name: entry.name,
  group: input.sectorCatalog.find((sector: any) => sector.name === entry.name)?.group ?? entry.group,
  // Full curated names only, no generic fragments or rank-derived fuzzy aliases.
  aliases: entry.name === "SafePal / Fiat24" ? ["SafePal"] : entry.name.split("／").filter((name: string) => name.length >= 3 && !ambiguous.has(name)),
}))
await Bun.write("到期管家/src/brand_catalog.ts", `// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. All rights reserved, subject to their exceptions.
// Generated by tools/build_runtime_brand_catalog.ts. Names are not artwork licenses.

export interface BrandDefinition { id: string; name: string; group: string; aliases: string[] }
export const BRAND_CATALOG: BrandDefinition[] = ${JSON.stringify(entries, null, 2)}
`)
console.log(`Generated ${entries.length} local brand choices`)
