// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. All rights reserved, subject to their exceptions.
import { join } from "node:path"
import { createHash } from "node:crypto"
import { BRAND_CATALOG } from "../到期管家/src/brand_catalog"
import { generateBrandFallbacks } from "./generate_brand_fallbacks"
const temporary = process.argv[2]
if(!temporary?.startsWith("/tmp/due-manager-complete-brands.")) throw Error("Task temp directory required")
const rows = await Bun.file(join(temporary,"preview.json")).json()
if(rows.length !== BRAND_CATALOG.length || rows.some((row:any)=>!row.selected)) throw Error("Full real-image coverage is required before bundling")
const root = join(import.meta.dir,"../到期管家")
const manifest = [], sources = [], embedded: Record<string,string> = {}
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex")
for(const brand of BRAND_CATALOG) {
  const row = rows.find((row:any)=>row.id === brand.id)
  if(!row || row.name !== brand.name) throw Error(`Unreviewed brand ${brand.name}`)
  const record = await Bun.file(join(temporary,"raw",`${brand.id}.json`)).json()
  const selected = row.selected
  const bytes = await Bun.file(selected.file).bytes()
  if(sha(bytes) !== selected.sha256) throw Error(`Raster changed after review: ${brand.name}`)
  let light = `assets/brands/${brand.id}.png`, dark = light, size = 24
  if(brand.id === "brand-04127553b4fb06d0") {
    light = "assets/brands/safepal-dark.png"; dark = "assets/brands/safepal-light.png"; size = 20
  } else if(brand.id === "brand-acdd1e734125f341") {
    light = "assets/brands/telegram.png"; dark = light
  } else await Bun.write(join(root,light),bytes)
  const outputs = []
  for(const path of [...new Set([light,dark])]) {
    const original = await Bun.file(join(root,path)).bytes()
    embedded[path] = Buffer.from(original).toString("base64")
    outputs.push({path,sha256:sha(original),bytes:original.length})
  }
  manifest.push({brandID:brand.id,light,dark,size})
  const special = brand.id === "brand-04127553b4fb06d0" || brand.id === "brand-acdd1e734125f341"
  sources.push({brandID:brand.id,name:brand.name,group:brand.group,outputs,
    source: special ? {type:"reviewed-original",details:"See SOURCES.md: original SafePal / Telegram assets retained unchanged from v2.6.0"}
      : {type:selected.sourceType,url:selected.url,basis:selected.basis,upstreamTitle:selected.upstreamTitle,
        appID:selected.appID,appName:selected.appName,seller:selected.seller,sellerURL:selected.sellerURL,
        inputSHA256:record.findings.find((finding:any)=>finding.filename === selected.input)?.sha256,
        upstreamSHA256:selected.upstreamSHA256,svgSymbol:selected.svgSymbol,
        originalWidth:selected.width,originalHeight:selected.height,color:selected.color,guidelines:selected.guidelines,license:selected.license},
    transformation:special?"None; original PNG bytes retained":(selected.svgSymbol?`Extracted named SVG symbol ${selected.svgSymbol} without changing its paths. `:"")+(selected.sourceType === "simple-icons"?`Monochrome SVG filled with upstream brand color #${selected.color}. `:"")+"Proportional rasterization to a 120 px box on a 144 px neutral backplate; original geometry retained, existing embedded colors preserved, unspecified SVG colors use renderer defaults. No AI redraw.",
    rights:"Brand artwork and trademarks remain with their respective rights holders. Source attribution is not a trademark license or a claim of endorsement."})
}
const header = "// SPDX-FileCopyrightText: 2026 MaroonYS\n// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0\n// See LICENSE and NOTICE.md. The above applies to the wrapper only, not third-party artwork.\n// Generated by tools/bundle_brand_assets.ts. Do not hand edit.\n// Brand image data remains with its rights holders; see assets/brands/SOURCES.md and manifest.json.\n"
await Bun.write(join(root,"src/brand_asset_manifest.ts"),header+'import type { BrandAsset } from "./brand_assets"\nexport const BRAND_ASSETS: BrandAsset[] = '+JSON.stringify(manifest,null,2)+"\n")
await Bun.write(join(root,"assets/brands/manifest.json"),JSON.stringify({schema:1,brandCount:sources.length,reviewedAt:new Date().toISOString(),assets:sources},null,2)+"\n")
await generateBrandFallbacks(root)
console.log(`Bundled ${manifest.length} brands, ${Object.keys(embedded).length} PNGs, ${Object.values(embedded).reduce((sum,data)=>sum+data.length,0)} base64 characters`)
