// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. The above applies to the wrapper only, not third-party artwork.
// Generated by tools/bundle_brand_assets.ts. Do not hand edit.
// Brand image data remains with its rights holders; see assets/brands/SOURCES.md and manifest.json.
import type { BrandAsset } from "./brand_assets"
export const BRAND_ASSETS: BrandAsset[] = [
  {
    "brandID": "brand-cf480cbb7a87b6d3",
    "light": "assets/brands/brand-cf480cbb7a87b6d3.png",
    "dark": "assets/brands/brand-cf480cbb7a87b6d3.png",
    "size": 24
  },
  {
    "brandID": "brand-1ae6e6416a7ad654",
    "light": "assets/brands/brand-1ae6e6416a7ad654.png",
    "dark": "assets/brands/brand-1ae6e6416a7ad654.png",
    "size": 24
  },
  {
    "brandID": "brand-952395274255063a",
    "light": "assets/brands/brand-952395274255063a.png",
    "dark": "assets/brands/brand-952395274255063a.png",
    "size": 24
  },
  {
    "brandID": "brand-1a34654a0c199abf",
    "light": "assets/brands/brand-1a34654a0c199abf.png",
    "dark": "assets/brands/brand-1a34654a0c199abf.png",
    "size": 24
  },
  {
    "brandID": "brand-e9591c52923895e2",
    "light": "assets/brands/brand-e9591c52923895e2.png",
    "dark": "assets/brands/brand-e9591c52923895e2.png",
    "size": 24
  },
  {
    "brandID": "brand-e2c258181616411e",
    "light": "assets/brands/brand-e2c258181616411e.png",
    "dark": "assets/brands/brand-e2c258181616411e.png",
    "size": 24
  },
  {
    "brandID": "brand-aa2c2fdc65c38b9f",
    "light": "assets/brands/brand-aa2c2fdc65c38b9f.png",
    "dark": "assets/brands/brand-aa2c2fdc65c38b9f.png",
    "size": 24
  },
  {
    "brandID": "brand-b21b93a4701fc767",
    "light": "assets/brands/brand-b21b93a4701fc767.png",
    "dark": "assets/brands/brand-b21b93a4701fc767.png",
    "size": 24
  },
  {
    "brandID": "brand-4cc4e63ced381bd7",
    "light": "assets/brands/brand-4cc4e63ced381bd7.png",
    "dark": "assets/brands/brand-4cc4e63ced381bd7.png",
    "size": 24
  },
  {
    "brandID": "brand-063fa0c03a82346c",
    "light": "assets/brands/brand-063fa0c03a82346c.png",
    "dark": "assets/brands/brand-063fa0c03a82346c.png",
    "size": 24
  },
  {
    "brandID": "brand-9e33f12992cab994",
    "light": "assets/brands/brand-9e33f12992cab994.png",
    "dark": "assets/brands/brand-9e33f12992cab994.png",
    "size": 24
  },
  {
    "brandID": "brand-e5ea46ebc1c7fa36",
    "light": "assets/brands/brand-e5ea46ebc1c7fa36.png",
    "dark": "assets/brands/brand-e5ea46ebc1c7fa36.png",
    "size": 24
  },
  {
    "brandID": "brand-e0f8aebbf712178d",
    "light": "assets/brands/brand-e0f8aebbf712178d.png",
    "dark": "assets/brands/brand-e0f8aebbf712178d.png",
    "size": 24
  },
  {
    "brandID": "brand-caf76992859b35e9",
    "light": "assets/brands/brand-caf76992859b35e9.png",
    "dark": "assets/brands/brand-caf76992859b35e9.png",
    "size": 24
  },
  {
    "brandID": "brand-3e87bc0a97f15971",
    "light": "assets/brands/brand-3e87bc0a97f15971.png",
    "dark": "assets/brands/brand-3e87bc0a97f15971.png",
    "size": 24
  },
  {
    "brandID": "brand-1de9de20ec4771e1",
    "light": "assets/brands/brand-1de9de20ec4771e1.png",
    "dark": "assets/brands/brand-1de9de20ec4771e1.png",
    "size": 24
  },
  {
    "brandID": "brand-f112198ca6d5bcfe",
    "light": "assets/brands/brand-f112198ca6d5bcfe.png",
    "dark": "assets/brands/brand-f112198ca6d5bcfe.png",
    "size": 24
  },
  {
    "brandID": "brand-d27f28e288e77b81",
    "light": "assets/brands/brand-d27f28e288e77b81.png",
    "dark": "assets/brands/brand-d27f28e288e77b81.png",
    "size": 24
  },
  {
    "brandID": "brand-d26d781218719c33",
    "light": "assets/brands/brand-d26d781218719c33.png",
    "dark": "assets/brands/brand-d26d781218719c33.png",
    "size": 24
  },
  {
    "brandID": "brand-65886f285b393964",
    "light": "assets/brands/brand-65886f285b393964.png",
    "dark": "assets/brands/brand-65886f285b393964.png",
    "size": 24
  },
  {
    "brandID": "brand-057fd3120b08c322",
    "light": "assets/brands/brand-057fd3120b08c322.png",
    "dark": "assets/brands/brand-057fd3120b08c322.png",
    "size": 24
  },
  {
    "brandID": "brand-d177ef7f1d911e4d",
    "light": "assets/brands/brand-d177ef7f1d911e4d.png",
    "dark": "assets/brands/brand-d177ef7f1d911e4d.png",
    "size": 24
  },
  {
    "brandID": "brand-b724ddcec8bc9cba",
    "light": "assets/brands/brand-b724ddcec8bc9cba.png",
    "dark": "assets/brands/brand-b724ddcec8bc9cba.png",
    "size": 24
  },
  {
    "brandID": "brand-5bd43e1a5086e677",
    "light": "assets/brands/brand-5bd43e1a5086e677.png",
    "dark": "assets/brands/brand-5bd43e1a5086e677.png",
    "size": 24
  },
  {
    "brandID": "brand-0b0594c9164b3972",
    "light": "assets/brands/brand-0b0594c9164b3972.png",
    "dark": "assets/brands/brand-0b0594c9164b3972.png",
    "size": 24
  },
  {
    "brandID": "brand-0f1b3c1321902d3e",
    "light": "assets/brands/brand-0f1b3c1321902d3e.png",
    "dark": "assets/brands/brand-0f1b3c1321902d3e.png",
    "size": 24
  },
  {
    "brandID": "brand-91a66b21430fc7f3",
    "light": "assets/brands/brand-91a66b21430fc7f3.png",
    "dark": "assets/brands/brand-91a66b21430fc7f3.png",
    "size": 24
  },
  {
    "brandID": "brand-c1974cbeaeaba234",
    "light": "assets/brands/brand-c1974cbeaeaba234.png",
    "dark": "assets/brands/brand-c1974cbeaeaba234.png",
    "size": 24
  },
  {
    "brandID": "brand-b56633823acf3bba",
    "light": "assets/brands/brand-b56633823acf3bba.png",
    "dark": "assets/brands/brand-b56633823acf3bba.png",
    "size": 24
  },
  {
    "brandID": "brand-53315e6525e54a82",
    "light": "assets/brands/brand-53315e6525e54a82.png",
    "dark": "assets/brands/brand-53315e6525e54a82.png",
    "size": 24
  },
  {
    "brandID": "brand-c9804bab8f7234ae",
    "light": "assets/brands/brand-c9804bab8f7234ae.png",
    "dark": "assets/brands/brand-c9804bab8f7234ae.png",
    "size": 24
  },
  {
    "brandID": "brand-08320ff72bfca8c2",
    "light": "assets/brands/brand-08320ff72bfca8c2.png",
    "dark": "assets/brands/brand-08320ff72bfca8c2.png",
    "size": 24
  },
  {
    "brandID": "brand-14539267d83df9ba",
    "light": "assets/brands/brand-14539267d83df9ba.png",
    "dark": "assets/brands/brand-14539267d83df9ba.png",
    "size": 24
  },
  {
    "brandID": "brand-824e367b5c775341",
    "light": "assets/brands/brand-824e367b5c775341.png",
    "dark": "assets/brands/brand-824e367b5c775341.png",
    "size": 24
  },
  {
    "brandID": "brand-476be3b21a3f22f1",
    "light": "assets/brands/brand-476be3b21a3f22f1.png",
    "dark": "assets/brands/brand-476be3b21a3f22f1.png",
    "size": 24
  },
  {
    "brandID": "brand-67831a00b4c103ff",
    "light": "assets/brands/brand-67831a00b4c103ff.png",
    "dark": "assets/brands/brand-67831a00b4c103ff.png",
    "size": 24
  },
  {
    "brandID": "brand-511722345a0668f6",
    "light": "assets/brands/brand-511722345a0668f6.png",
    "dark": "assets/brands/brand-511722345a0668f6.png",
    "size": 24
  },
  {
    "brandID": "brand-5aed45c196178dc6",
    "light": "assets/brands/brand-5aed45c196178dc6.png",
    "dark": "assets/brands/brand-5aed45c196178dc6.png",
    "size": 24
  },
  {
    "brandID": "brand-73a7c5c1df6eb4ce",
    "light": "assets/brands/brand-73a7c5c1df6eb4ce.png",
    "dark": "assets/brands/brand-73a7c5c1df6eb4ce.png",
    "size": 24
  },
  {
    "brandID": "brand-07500f3dc48a89e4",
    "light": "assets/brands/brand-07500f3dc48a89e4.png",
    "dark": "assets/brands/brand-07500f3dc48a89e4.png",
    "size": 24
  },
  {
    "brandID": "brand-1933d4a79708d932",
    "light": "assets/brands/brand-1933d4a79708d932.png",
    "dark": "assets/brands/brand-1933d4a79708d932.png",
    "size": 24
  },
  {
    "brandID": "brand-b12733a5d63d7501",
    "light": "assets/brands/brand-b12733a5d63d7501.png",
    "dark": "assets/brands/brand-b12733a5d63d7501.png",
    "size": 24
  },
  {
    "brandID": "brand-9a4230bbe97192a3",
    "light": "assets/brands/brand-9a4230bbe97192a3.png",
    "dark": "assets/brands/brand-9a4230bbe97192a3.png",
    "size": 24
  },
  {
    "brandID": "brand-06a29a2f2e44bf79",
    "light": "assets/brands/brand-06a29a2f2e44bf79.png",
    "dark": "assets/brands/brand-06a29a2f2e44bf79.png",
    "size": 24
  },
  {
    "brandID": "brand-b3b438c24d962a0f",
    "light": "assets/brands/brand-b3b438c24d962a0f.png",
    "dark": "assets/brands/brand-b3b438c24d962a0f.png",
    "size": 24
  },
  {
    "brandID": "brand-b75732aa0f91e735",
    "light": "assets/brands/brand-b75732aa0f91e735.png",
    "dark": "assets/brands/brand-b75732aa0f91e735.png",
    "size": 24
  },
  {
    "brandID": "brand-d12e6a419c206aea",
    "light": "assets/brands/brand-d12e6a419c206aea.png",
    "dark": "assets/brands/brand-d12e6a419c206aea.png",
    "size": 24
  },
  {
    "brandID": "brand-ab8a4f6bb84d161b",
    "light": "assets/brands/brand-ab8a4f6bb84d161b.png",
    "dark": "assets/brands/brand-ab8a4f6bb84d161b.png",
    "size": 24
  },
  {
    "brandID": "brand-2105f7da1289e2d2",
    "light": "assets/brands/brand-2105f7da1289e2d2.png",
    "dark": "assets/brands/brand-2105f7da1289e2d2.png",
    "size": 24
  },
  {
    "brandID": "brand-a1593ecc5a13b7a0",
    "light": "assets/brands/brand-a1593ecc5a13b7a0.png",
    "dark": "assets/brands/brand-a1593ecc5a13b7a0.png",
    "size": 24
  },
  {
    "brandID": "brand-a2e779358d0d0fdf",
    "light": "assets/brands/brand-a2e779358d0d0fdf.png",
    "dark": "assets/brands/brand-a2e779358d0d0fdf.png",
    "size": 24
  },
  {
    "brandID": "brand-dd53271a2e067540",
    "light": "assets/brands/brand-dd53271a2e067540.png",
    "dark": "assets/brands/brand-dd53271a2e067540.png",
    "size": 24
  },
  {
    "brandID": "brand-e3fcf621116d3fe8",
    "light": "assets/brands/brand-e3fcf621116d3fe8.png",
    "dark": "assets/brands/brand-e3fcf621116d3fe8.png",
    "size": 24
  },
  {
    "brandID": "brand-276a8bc458036a1a",
    "light": "assets/brands/brand-276a8bc458036a1a.png",
    "dark": "assets/brands/brand-276a8bc458036a1a.png",
    "size": 24
  },
  {
    "brandID": "brand-a01544d8fc145a8a",
    "light": "assets/brands/brand-a01544d8fc145a8a.png",
    "dark": "assets/brands/brand-a01544d8fc145a8a.png",
    "size": 24
  },
  {
    "brandID": "brand-d8a403a5d9abf615",
    "light": "assets/brands/brand-d8a403a5d9abf615.png",
    "dark": "assets/brands/brand-d8a403a5d9abf615.png",
    "size": 24
  },
  {
    "brandID": "brand-6419de732fece5d6",
    "light": "assets/brands/brand-6419de732fece5d6.png",
    "dark": "assets/brands/brand-6419de732fece5d6.png",
    "size": 24
  },
  {
    "brandID": "brand-0103f5d08eede1fb",
    "light": "assets/brands/brand-0103f5d08eede1fb.png",
    "dark": "assets/brands/brand-0103f5d08eede1fb.png",
    "size": 24
  },
  {
    "brandID": "brand-41c8b2ad4b7c7387",
    "light": "assets/brands/brand-41c8b2ad4b7c7387.png",
    "dark": "assets/brands/brand-41c8b2ad4b7c7387.png",
    "size": 24
  },
  {
    "brandID": "brand-52b22789c4c6e72b",
    "light": "assets/brands/brand-52b22789c4c6e72b.png",
    "dark": "assets/brands/brand-52b22789c4c6e72b.png",
    "size": 24
  },
  {
    "brandID": "brand-14eba0693bf48744",
    "light": "assets/brands/brand-14eba0693bf48744.png",
    "dark": "assets/brands/brand-14eba0693bf48744.png",
    "size": 24
  },
  {
    "brandID": "brand-11f3b69f9934166e",
    "light": "assets/brands/brand-11f3b69f9934166e.png",
    "dark": "assets/brands/brand-11f3b69f9934166e.png",
    "size": 24
  },
  {
    "brandID": "brand-0cfc3bb8500974c3",
    "light": "assets/brands/brand-0cfc3bb8500974c3.png",
    "dark": "assets/brands/brand-0cfc3bb8500974c3.png",
    "size": 24
  },
  {
    "brandID": "brand-95a4f01c0350d730",
    "light": "assets/brands/brand-95a4f01c0350d730.png",
    "dark": "assets/brands/brand-95a4f01c0350d730.png",
    "size": 24
  },
  {
    "brandID": "brand-ab43fc6eec59a19c",
    "light": "assets/brands/brand-ab43fc6eec59a19c.png",
    "dark": "assets/brands/brand-ab43fc6eec59a19c.png",
    "size": 24
  },
  {
    "brandID": "brand-c21bea0c6d590524",
    "light": "assets/brands/brand-c21bea0c6d590524.png",
    "dark": "assets/brands/brand-c21bea0c6d590524.png",
    "size": 24
  },
  {
    "brandID": "brand-66519047f5733551",
    "light": "assets/brands/brand-66519047f5733551.png",
    "dark": "assets/brands/brand-66519047f5733551.png",
    "size": 24
  },
  {
    "brandID": "brand-839b21c9cdc163c9",
    "light": "assets/brands/brand-839b21c9cdc163c9.png",
    "dark": "assets/brands/brand-839b21c9cdc163c9.png",
    "size": 24
  },
  {
    "brandID": "brand-ef1dcffbcfe38fef",
    "light": "assets/brands/brand-ef1dcffbcfe38fef.png",
    "dark": "assets/brands/brand-ef1dcffbcfe38fef.png",
    "size": 24
  },
  {
    "brandID": "brand-dfb80b004c96aa54",
    "light": "assets/brands/brand-dfb80b004c96aa54.png",
    "dark": "assets/brands/brand-dfb80b004c96aa54.png",
    "size": 24
  },
  {
    "brandID": "brand-320183649dde9491",
    "light": "assets/brands/brand-320183649dde9491.png",
    "dark": "assets/brands/brand-320183649dde9491.png",
    "size": 24
  },
  {
    "brandID": "brand-8da288304fae9a78",
    "light": "assets/brands/brand-8da288304fae9a78.png",
    "dark": "assets/brands/brand-8da288304fae9a78.png",
    "size": 24
  },
  {
    "brandID": "brand-3adf3250d46ff48f",
    "light": "assets/brands/brand-3adf3250d46ff48f.png",
    "dark": "assets/brands/brand-3adf3250d46ff48f.png",
    "size": 24
  },
  {
    "brandID": "brand-89b531787b023e79",
    "light": "assets/brands/brand-89b531787b023e79.png",
    "dark": "assets/brands/brand-89b531787b023e79.png",
    "size": 24
  },
  {
    "brandID": "brand-50a4122943273ad2",
    "light": "assets/brands/brand-50a4122943273ad2.png",
    "dark": "assets/brands/brand-50a4122943273ad2.png",
    "size": 24
  },
  {
    "brandID": "brand-0615570f9ea13694",
    "light": "assets/brands/brand-0615570f9ea13694.png",
    "dark": "assets/brands/brand-0615570f9ea13694.png",
    "size": 24
  },
  {
    "brandID": "brand-063b734802746476",
    "light": "assets/brands/brand-063b734802746476.png",
    "dark": "assets/brands/brand-063b734802746476.png",
    "size": 24
  },
  {
    "brandID": "brand-dca61d32363b091b",
    "light": "assets/brands/brand-dca61d32363b091b.png",
    "dark": "assets/brands/brand-dca61d32363b091b.png",
    "size": 24
  },
  {
    "brandID": "brand-0648d2111ec0ca3d",
    "light": "assets/brands/brand-0648d2111ec0ca3d.png",
    "dark": "assets/brands/brand-0648d2111ec0ca3d.png",
    "size": 24
  },
  {
    "brandID": "brand-f64660efbe61dd28",
    "light": "assets/brands/brand-f64660efbe61dd28.png",
    "dark": "assets/brands/brand-f64660efbe61dd28.png",
    "size": 24
  },
  {
    "brandID": "brand-db2d53fb1c9cf5fb",
    "light": "assets/brands/brand-db2d53fb1c9cf5fb.png",
    "dark": "assets/brands/brand-db2d53fb1c9cf5fb.png",
    "size": 24
  },
  {
    "brandID": "brand-83f10a44727fc929",
    "light": "assets/brands/brand-83f10a44727fc929.png",
    "dark": "assets/brands/brand-83f10a44727fc929.png",
    "size": 24
  },
  {
    "brandID": "brand-f394cc2a6da7dfd6",
    "light": "assets/brands/brand-f394cc2a6da7dfd6.png",
    "dark": "assets/brands/brand-f394cc2a6da7dfd6.png",
    "size": 24
  },
  {
    "brandID": "brand-f09f149fa26808f8",
    "light": "assets/brands/brand-f09f149fa26808f8.png",
    "dark": "assets/brands/brand-f09f149fa26808f8.png",
    "size": 24
  },
  {
    "brandID": "brand-02dc2a9874362dcb",
    "light": "assets/brands/brand-02dc2a9874362dcb.png",
    "dark": "assets/brands/brand-02dc2a9874362dcb.png",
    "size": 24
  },
  {
    "brandID": "brand-681515c24531ca81",
    "light": "assets/brands/brand-681515c24531ca81.png",
    "dark": "assets/brands/brand-681515c24531ca81.png",
    "size": 24
  },
  {
    "brandID": "brand-d3b7d7dd5caec996",
    "light": "assets/brands/brand-d3b7d7dd5caec996.png",
    "dark": "assets/brands/brand-d3b7d7dd5caec996.png",
    "size": 24
  },
  {
    "brandID": "brand-61f2c2a36de1f845",
    "light": "assets/brands/brand-61f2c2a36de1f845.png",
    "dark": "assets/brands/brand-61f2c2a36de1f845.png",
    "size": 24
  },
  {
    "brandID": "brand-69e77a2d45ecb210",
    "light": "assets/brands/brand-69e77a2d45ecb210.png",
    "dark": "assets/brands/brand-69e77a2d45ecb210.png",
    "size": 24
  },
  {
    "brandID": "brand-20ddfb33ebb13fd7",
    "light": "assets/brands/brand-20ddfb33ebb13fd7.png",
    "dark": "assets/brands/brand-20ddfb33ebb13fd7.png",
    "size": 24
  },
  {
    "brandID": "brand-590a5961464ddf6e",
    "light": "assets/brands/brand-590a5961464ddf6e.png",
    "dark": "assets/brands/brand-590a5961464ddf6e.png",
    "size": 24
  },
  {
    "brandID": "brand-67a67fc05f47b36e",
    "light": "assets/brands/brand-67a67fc05f47b36e.png",
    "dark": "assets/brands/brand-67a67fc05f47b36e.png",
    "size": 24
  },
  {
    "brandID": "brand-d50d4c56ce50ac9d",
    "light": "assets/brands/brand-d50d4c56ce50ac9d.png",
    "dark": "assets/brands/brand-d50d4c56ce50ac9d.png",
    "size": 24
  },
  {
    "brandID": "brand-cfc3d445066f6e83",
    "light": "assets/brands/brand-cfc3d445066f6e83.png",
    "dark": "assets/brands/brand-cfc3d445066f6e83.png",
    "size": 24
  },
  {
    "brandID": "brand-7005c0064bda4edb",
    "light": "assets/brands/brand-7005c0064bda4edb.png",
    "dark": "assets/brands/brand-7005c0064bda4edb.png",
    "size": 24
  },
  {
    "brandID": "brand-6921a7cac539977d",
    "light": "assets/brands/brand-6921a7cac539977d.png",
    "dark": "assets/brands/brand-6921a7cac539977d.png",
    "size": 24
  },
  {
    "brandID": "brand-3ef42060a2e523ab",
    "light": "assets/brands/brand-3ef42060a2e523ab.png",
    "dark": "assets/brands/brand-3ef42060a2e523ab.png",
    "size": 24
  },
  {
    "brandID": "brand-4a366fb92e537bad",
    "light": "assets/brands/brand-4a366fb92e537bad.png",
    "dark": "assets/brands/brand-4a366fb92e537bad.png",
    "size": 24
  },
  {
    "brandID": "brand-7d0e8317588d3aec",
    "light": "assets/brands/brand-7d0e8317588d3aec.png",
    "dark": "assets/brands/brand-7d0e8317588d3aec.png",
    "size": 24
  },
  {
    "brandID": "brand-f8cff81f622364ff",
    "light": "assets/brands/brand-f8cff81f622364ff.png",
    "dark": "assets/brands/brand-f8cff81f622364ff.png",
    "size": 24
  },
  {
    "brandID": "brand-8506b11e2d839545",
    "light": "assets/brands/brand-8506b11e2d839545.png",
    "dark": "assets/brands/brand-8506b11e2d839545.png",
    "size": 24
  },
  {
    "brandID": "brand-0f622ac0d0500ae8",
    "light": "assets/brands/brand-0f622ac0d0500ae8.png",
    "dark": "assets/brands/brand-0f622ac0d0500ae8.png",
    "size": 24
  },
  {
    "brandID": "brand-4c57d8f0e66cbc66",
    "light": "assets/brands/brand-4c57d8f0e66cbc66.png",
    "dark": "assets/brands/brand-4c57d8f0e66cbc66.png",
    "size": 24
  },
  {
    "brandID": "brand-a7b52b269a23c025",
    "light": "assets/brands/brand-a7b52b269a23c025.png",
    "dark": "assets/brands/brand-a7b52b269a23c025.png",
    "size": 24
  },
  {
    "brandID": "brand-509c517ede79fef0",
    "light": "assets/brands/brand-509c517ede79fef0.png",
    "dark": "assets/brands/brand-509c517ede79fef0.png",
    "size": 24
  },
  {
    "brandID": "brand-f3943a7b368154d1",
    "light": "assets/brands/brand-f3943a7b368154d1.png",
    "dark": "assets/brands/brand-f3943a7b368154d1.png",
    "size": 24
  },
  {
    "brandID": "brand-27389885c97c4ab1",
    "light": "assets/brands/brand-27389885c97c4ab1.png",
    "dark": "assets/brands/brand-27389885c97c4ab1.png",
    "size": 24
  },
  {
    "brandID": "brand-7e4419d1de251094",
    "light": "assets/brands/brand-7e4419d1de251094.png",
    "dark": "assets/brands/brand-7e4419d1de251094.png",
    "size": 24
  },
  {
    "brandID": "brand-b27fb38ba323745c",
    "light": "assets/brands/brand-b27fb38ba323745c.png",
    "dark": "assets/brands/brand-b27fb38ba323745c.png",
    "size": 24
  },
  {
    "brandID": "brand-accbbc4e5d81fff0",
    "light": "assets/brands/brand-accbbc4e5d81fff0.png",
    "dark": "assets/brands/brand-accbbc4e5d81fff0.png",
    "size": 24
  },
  {
    "brandID": "brand-73bcfe98830b53a1",
    "light": "assets/brands/brand-73bcfe98830b53a1.png",
    "dark": "assets/brands/brand-73bcfe98830b53a1.png",
    "size": 24
  },
  {
    "brandID": "brand-7b836ff8388ef97c",
    "light": "assets/brands/brand-7b836ff8388ef97c.png",
    "dark": "assets/brands/brand-7b836ff8388ef97c.png",
    "size": 24
  },
  {
    "brandID": "brand-915ef4bad59a1329",
    "light": "assets/brands/brand-915ef4bad59a1329.png",
    "dark": "assets/brands/brand-915ef4bad59a1329.png",
    "size": 24
  },
  {
    "brandID": "brand-4750d0a12e03a1be",
    "light": "assets/brands/brand-4750d0a12e03a1be.png",
    "dark": "assets/brands/brand-4750d0a12e03a1be.png",
    "size": 24
  },
  {
    "brandID": "brand-8a7a54d38f1a7e32",
    "light": "assets/brands/brand-8a7a54d38f1a7e32.png",
    "dark": "assets/brands/brand-8a7a54d38f1a7e32.png",
    "size": 24
  },
  {
    "brandID": "brand-b5eaa6e7444f6dd7",
    "light": "assets/brands/brand-b5eaa6e7444f6dd7.png",
    "dark": "assets/brands/brand-b5eaa6e7444f6dd7.png",
    "size": 24
  },
  {
    "brandID": "brand-e9665f54d274f44e",
    "light": "assets/brands/brand-e9665f54d274f44e.png",
    "dark": "assets/brands/brand-e9665f54d274f44e.png",
    "size": 24
  },
  {
    "brandID": "brand-d5291dd3ee13f829",
    "light": "assets/brands/brand-d5291dd3ee13f829.png",
    "dark": "assets/brands/brand-d5291dd3ee13f829.png",
    "size": 24
  },
  {
    "brandID": "brand-2f73335c712c9214",
    "light": "assets/brands/brand-2f73335c712c9214.png",
    "dark": "assets/brands/brand-2f73335c712c9214.png",
    "size": 24
  },
  {
    "brandID": "brand-093c2597d7f28f73",
    "light": "assets/brands/brand-093c2597d7f28f73.png",
    "dark": "assets/brands/brand-093c2597d7f28f73.png",
    "size": 24
  },
  {
    "brandID": "brand-1afc8bb18decc6dd",
    "light": "assets/brands/brand-1afc8bb18decc6dd.png",
    "dark": "assets/brands/brand-1afc8bb18decc6dd.png",
    "size": 24
  },
  {
    "brandID": "brand-60a648def576a07e",
    "light": "assets/brands/brand-60a648def576a07e.png",
    "dark": "assets/brands/brand-60a648def576a07e.png",
    "size": 24
  },
  {
    "brandID": "brand-d1cd971aa6f69253",
    "light": "assets/brands/brand-d1cd971aa6f69253.png",
    "dark": "assets/brands/brand-d1cd971aa6f69253.png",
    "size": 24
  },
  {
    "brandID": "brand-ce46041005a8aa0d",
    "light": "assets/brands/brand-ce46041005a8aa0d.png",
    "dark": "assets/brands/brand-ce46041005a8aa0d.png",
    "size": 24
  },
  {
    "brandID": "brand-b48c1831a03feab8",
    "light": "assets/brands/brand-b48c1831a03feab8.png",
    "dark": "assets/brands/brand-b48c1831a03feab8.png",
    "size": 24
  },
  {
    "brandID": "brand-e9aa6f761190f23c",
    "light": "assets/brands/brand-e9aa6f761190f23c.png",
    "dark": "assets/brands/brand-e9aa6f761190f23c.png",
    "size": 24
  },
  {
    "brandID": "brand-1e67b40f2d64665d",
    "light": "assets/brands/brand-1e67b40f2d64665d.png",
    "dark": "assets/brands/brand-1e67b40f2d64665d.png",
    "size": 24
  },
  {
    "brandID": "brand-183f00f483d3844e",
    "light": "assets/brands/brand-183f00f483d3844e.png",
    "dark": "assets/brands/brand-183f00f483d3844e.png",
    "size": 24
  },
  {
    "brandID": "brand-e5879951eb998dab",
    "light": "assets/brands/brand-e5879951eb998dab.png",
    "dark": "assets/brands/brand-e5879951eb998dab.png",
    "size": 24
  },
  {
    "brandID": "brand-38f6b83e2dc175c7",
    "light": "assets/brands/brand-38f6b83e2dc175c7.png",
    "dark": "assets/brands/brand-38f6b83e2dc175c7.png",
    "size": 24
  },
  {
    "brandID": "brand-8e9b845f943fc8b0",
    "light": "assets/brands/brand-8e9b845f943fc8b0.png",
    "dark": "assets/brands/brand-8e9b845f943fc8b0.png",
    "size": 24
  },
  {
    "brandID": "brand-a3651e8fe91621dd",
    "light": "assets/brands/brand-a3651e8fe91621dd.png",
    "dark": "assets/brands/brand-a3651e8fe91621dd.png",
    "size": 24
  },
  {
    "brandID": "brand-616aec2ec9eccc74",
    "light": "assets/brands/brand-616aec2ec9eccc74.png",
    "dark": "assets/brands/brand-616aec2ec9eccc74.png",
    "size": 24
  },
  {
    "brandID": "brand-be433280de3a4365",
    "light": "assets/brands/brand-be433280de3a4365.png",
    "dark": "assets/brands/brand-be433280de3a4365.png",
    "size": 24
  },
  {
    "brandID": "brand-0f686f85f586c202",
    "light": "assets/brands/brand-0f686f85f586c202.png",
    "dark": "assets/brands/brand-0f686f85f586c202.png",
    "size": 24
  },
  {
    "brandID": "brand-3eab285c90aa3223",
    "light": "assets/brands/brand-3eab285c90aa3223.png",
    "dark": "assets/brands/brand-3eab285c90aa3223.png",
    "size": 24
  },
  {
    "brandID": "brand-81baf57e05f11276",
    "light": "assets/brands/brand-81baf57e05f11276.png",
    "dark": "assets/brands/brand-81baf57e05f11276.png",
    "size": 24
  },
  {
    "brandID": "brand-da14d8f7500f7e61",
    "light": "assets/brands/brand-da14d8f7500f7e61.png",
    "dark": "assets/brands/brand-da14d8f7500f7e61.png",
    "size": 24
  },
  {
    "brandID": "brand-fad070cff2ed8a64",
    "light": "assets/brands/brand-fad070cff2ed8a64.png",
    "dark": "assets/brands/brand-fad070cff2ed8a64.png",
    "size": 24
  },
  {
    "brandID": "brand-effea4c9ff35497c",
    "light": "assets/brands/brand-effea4c9ff35497c.png",
    "dark": "assets/brands/brand-effea4c9ff35497c.png",
    "size": 24
  },
  {
    "brandID": "brand-4150177b54900ee8",
    "light": "assets/brands/brand-4150177b54900ee8.png",
    "dark": "assets/brands/brand-4150177b54900ee8.png",
    "size": 24
  },
  {
    "brandID": "brand-268d99ac6debb8a0",
    "light": "assets/brands/brand-268d99ac6debb8a0.png",
    "dark": "assets/brands/brand-268d99ac6debb8a0.png",
    "size": 24
  },
  {
    "brandID": "brand-1081fdaaeceae9d9",
    "light": "assets/brands/brand-1081fdaaeceae9d9.png",
    "dark": "assets/brands/brand-1081fdaaeceae9d9.png",
    "size": 24
  },
  {
    "brandID": "brand-153091ce6e774499",
    "light": "assets/brands/brand-153091ce6e774499.png",
    "dark": "assets/brands/brand-153091ce6e774499.png",
    "size": 24
  },
  {
    "brandID": "brand-31263a45e794c7a4",
    "light": "assets/brands/brand-31263a45e794c7a4.png",
    "dark": "assets/brands/brand-31263a45e794c7a4.png",
    "size": 24
  },
  {
    "brandID": "brand-cd6362472aea60ef",
    "light": "assets/brands/brand-cd6362472aea60ef.png",
    "dark": "assets/brands/brand-cd6362472aea60ef.png",
    "size": 24
  },
  {
    "brandID": "brand-3cfbdbc3ba7620f9",
    "light": "assets/brands/brand-3cfbdbc3ba7620f9.png",
    "dark": "assets/brands/brand-3cfbdbc3ba7620f9.png",
    "size": 24
  },
  {
    "brandID": "brand-571ce0217afc888b",
    "light": "assets/brands/brand-571ce0217afc888b.png",
    "dark": "assets/brands/brand-571ce0217afc888b.png",
    "size": 24
  },
  {
    "brandID": "brand-1d927621f5321e99",
    "light": "assets/brands/brand-1d927621f5321e99.png",
    "dark": "assets/brands/brand-1d927621f5321e99.png",
    "size": 24
  },
  {
    "brandID": "brand-04a109180efc63cb",
    "light": "assets/brands/brand-04a109180efc63cb.png",
    "dark": "assets/brands/brand-04a109180efc63cb.png",
    "size": 24
  },
  {
    "brandID": "brand-49233b820253f8ef",
    "light": "assets/brands/brand-49233b820253f8ef.png",
    "dark": "assets/brands/brand-49233b820253f8ef.png",
    "size": 24
  },
  {
    "brandID": "brand-57b33bc4f2a1d871",
    "light": "assets/brands/brand-57b33bc4f2a1d871.png",
    "dark": "assets/brands/brand-57b33bc4f2a1d871.png",
    "size": 24
  },
  {
    "brandID": "brand-741765d017c050cf",
    "light": "assets/brands/brand-741765d017c050cf.png",
    "dark": "assets/brands/brand-741765d017c050cf.png",
    "size": 24
  },
  {
    "brandID": "brand-fc7b67fc71014fff",
    "light": "assets/brands/brand-fc7b67fc71014fff.png",
    "dark": "assets/brands/brand-fc7b67fc71014fff.png",
    "size": 24
  },
  {
    "brandID": "brand-2923740fe800e250",
    "light": "assets/brands/brand-2923740fe800e250.png",
    "dark": "assets/brands/brand-2923740fe800e250.png",
    "size": 24
  },
  {
    "brandID": "brand-1ecb3ba10a167e3c",
    "light": "assets/brands/brand-1ecb3ba10a167e3c.png",
    "dark": "assets/brands/brand-1ecb3ba10a167e3c.png",
    "size": 24
  },
  {
    "brandID": "brand-302415affc9a5568",
    "light": "assets/brands/brand-302415affc9a5568.png",
    "dark": "assets/brands/brand-302415affc9a5568.png",
    "size": 24
  },
  {
    "brandID": "brand-aa7899c7c392113a",
    "light": "assets/brands/brand-aa7899c7c392113a.png",
    "dark": "assets/brands/brand-aa7899c7c392113a.png",
    "size": 24
  },
  {
    "brandID": "brand-0453b8f9e9b20902",
    "light": "assets/brands/brand-0453b8f9e9b20902.png",
    "dark": "assets/brands/brand-0453b8f9e9b20902.png",
    "size": 24
  },
  {
    "brandID": "brand-343856a7c4d78fa0",
    "light": "assets/brands/brand-343856a7c4d78fa0.png",
    "dark": "assets/brands/brand-343856a7c4d78fa0.png",
    "size": 24
  },
  {
    "brandID": "brand-3c1f52eeebdc4db1",
    "light": "assets/brands/brand-3c1f52eeebdc4db1.png",
    "dark": "assets/brands/brand-3c1f52eeebdc4db1.png",
    "size": 24
  },
  {
    "brandID": "brand-47a414e6183a3751",
    "light": "assets/brands/brand-47a414e6183a3751.png",
    "dark": "assets/brands/brand-47a414e6183a3751.png",
    "size": 24
  },
  {
    "brandID": "brand-b1bc56450f0bc098",
    "light": "assets/brands/brand-b1bc56450f0bc098.png",
    "dark": "assets/brands/brand-b1bc56450f0bc098.png",
    "size": 24
  },
  {
    "brandID": "brand-92b4440b37d35124",
    "light": "assets/brands/brand-92b4440b37d35124.png",
    "dark": "assets/brands/brand-92b4440b37d35124.png",
    "size": 24
  },
  {
    "brandID": "brand-987dccf2ea2b28cc",
    "light": "assets/brands/brand-987dccf2ea2b28cc.png",
    "dark": "assets/brands/brand-987dccf2ea2b28cc.png",
    "size": 24
  },
  {
    "brandID": "brand-ae322cc596675baf",
    "light": "assets/brands/brand-ae322cc596675baf.png",
    "dark": "assets/brands/brand-ae322cc596675baf.png",
    "size": 24
  },
  {
    "brandID": "brand-8b970e423d67e179",
    "light": "assets/brands/brand-8b970e423d67e179.png",
    "dark": "assets/brands/brand-8b970e423d67e179.png",
    "size": 24
  },
  {
    "brandID": "brand-cef48094c18a91b3",
    "light": "assets/brands/brand-cef48094c18a91b3.png",
    "dark": "assets/brands/brand-cef48094c18a91b3.png",
    "size": 24
  },
  {
    "brandID": "brand-3475ef3028c08f26",
    "light": "assets/brands/brand-3475ef3028c08f26.png",
    "dark": "assets/brands/brand-3475ef3028c08f26.png",
    "size": 24
  },
  {
    "brandID": "brand-e5c07c1fdd938261",
    "light": "assets/brands/brand-e5c07c1fdd938261.png",
    "dark": "assets/brands/brand-e5c07c1fdd938261.png",
    "size": 24
  },
  {
    "brandID": "brand-d34fd66d3ef962bb",
    "light": "assets/brands/brand-d34fd66d3ef962bb.png",
    "dark": "assets/brands/brand-d34fd66d3ef962bb.png",
    "size": 24
  },
  {
    "brandID": "brand-d44f5b3e24a6da0d",
    "light": "assets/brands/brand-d44f5b3e24a6da0d.png",
    "dark": "assets/brands/brand-d44f5b3e24a6da0d.png",
    "size": 24
  },
  {
    "brandID": "brand-8c339ec81c3ea691",
    "light": "assets/brands/brand-8c339ec81c3ea691.png",
    "dark": "assets/brands/brand-8c339ec81c3ea691.png",
    "size": 24
  },
  {
    "brandID": "brand-3ed3fdfdbbc9f018",
    "light": "assets/brands/brand-3ed3fdfdbbc9f018.png",
    "dark": "assets/brands/brand-3ed3fdfdbbc9f018.png",
    "size": 24
  },
  {
    "brandID": "brand-81b430b696435180",
    "light": "assets/brands/brand-81b430b696435180.png",
    "dark": "assets/brands/brand-81b430b696435180.png",
    "size": 24
  },
  {
    "brandID": "brand-2f04a3aa051f1f60",
    "light": "assets/brands/brand-2f04a3aa051f1f60.png",
    "dark": "assets/brands/brand-2f04a3aa051f1f60.png",
    "size": 24
  },
  {
    "brandID": "brand-acdd1e734125f341",
    "light": "assets/brands/telegram.png",
    "dark": "assets/brands/telegram.png",
    "size": 24
  },
  {
    "brandID": "brand-053bc65874ad6098",
    "light": "assets/brands/brand-053bc65874ad6098.png",
    "dark": "assets/brands/brand-053bc65874ad6098.png",
    "size": 24
  },
  {
    "brandID": "brand-dd84425b72da12c6",
    "light": "assets/brands/brand-dd84425b72da12c6.png",
    "dark": "assets/brands/brand-dd84425b72da12c6.png",
    "size": 24
  },
  {
    "brandID": "brand-ac7606ebfd021341",
    "light": "assets/brands/brand-ac7606ebfd021341.png",
    "dark": "assets/brands/brand-ac7606ebfd021341.png",
    "size": 24
  },
  {
    "brandID": "brand-8d10b64d749d7e27",
    "light": "assets/brands/brand-8d10b64d749d7e27.png",
    "dark": "assets/brands/brand-8d10b64d749d7e27.png",
    "size": 24
  },
  {
    "brandID": "brand-cbbea9d808ebfe70",
    "light": "assets/brands/brand-cbbea9d808ebfe70.png",
    "dark": "assets/brands/brand-cbbea9d808ebfe70.png",
    "size": 24
  },
  {
    "brandID": "brand-8d0fc70cea9187c6",
    "light": "assets/brands/brand-8d0fc70cea9187c6.png",
    "dark": "assets/brands/brand-8d0fc70cea9187c6.png",
    "size": 24
  },
  {
    "brandID": "brand-7b88db3210925677",
    "light": "assets/brands/brand-7b88db3210925677.png",
    "dark": "assets/brands/brand-7b88db3210925677.png",
    "size": 24
  },
  {
    "brandID": "brand-0684c4f2a2f949a3",
    "light": "assets/brands/brand-0684c4f2a2f949a3.png",
    "dark": "assets/brands/brand-0684c4f2a2f949a3.png",
    "size": 24
  },
  {
    "brandID": "brand-f911e414cf6bdfc5",
    "light": "assets/brands/brand-f911e414cf6bdfc5.png",
    "dark": "assets/brands/brand-f911e414cf6bdfc5.png",
    "size": 24
  },
  {
    "brandID": "brand-601a29658a2d36c4",
    "light": "assets/brands/brand-601a29658a2d36c4.png",
    "dark": "assets/brands/brand-601a29658a2d36c4.png",
    "size": 24
  },
  {
    "brandID": "brand-6453a64fc695d701",
    "light": "assets/brands/brand-6453a64fc695d701.png",
    "dark": "assets/brands/brand-6453a64fc695d701.png",
    "size": 24
  },
  {
    "brandID": "brand-b83ec2d41f6fcc75",
    "light": "assets/brands/brand-b83ec2d41f6fcc75.png",
    "dark": "assets/brands/brand-b83ec2d41f6fcc75.png",
    "size": 24
  },
  {
    "brandID": "brand-c5b1c5d04a058c3f",
    "light": "assets/brands/brand-c5b1c5d04a058c3f.png",
    "dark": "assets/brands/brand-c5b1c5d04a058c3f.png",
    "size": 24
  },
  {
    "brandID": "brand-33b47af199c327fc",
    "light": "assets/brands/brand-33b47af199c327fc.png",
    "dark": "assets/brands/brand-33b47af199c327fc.png",
    "size": 24
  },
  {
    "brandID": "brand-934ee512583692b2",
    "light": "assets/brands/brand-934ee512583692b2.png",
    "dark": "assets/brands/brand-934ee512583692b2.png",
    "size": 24
  },
  {
    "brandID": "brand-2837e282166f3c5d",
    "light": "assets/brands/brand-2837e282166f3c5d.png",
    "dark": "assets/brands/brand-2837e282166f3c5d.png",
    "size": 24
  },
  {
    "brandID": "brand-f3d8869ce3625d21",
    "light": "assets/brands/brand-f3d8869ce3625d21.png",
    "dark": "assets/brands/brand-f3d8869ce3625d21.png",
    "size": 24
  },
  {
    "brandID": "brand-7e0d951b2b392798",
    "light": "assets/brands/brand-7e0d951b2b392798.png",
    "dark": "assets/brands/brand-7e0d951b2b392798.png",
    "size": 24
  },
  {
    "brandID": "brand-17c0481b40d09071",
    "light": "assets/brands/brand-17c0481b40d09071.png",
    "dark": "assets/brands/brand-17c0481b40d09071.png",
    "size": 24
  },
  {
    "brandID": "brand-47358d382f26024e",
    "light": "assets/brands/brand-47358d382f26024e.png",
    "dark": "assets/brands/brand-47358d382f26024e.png",
    "size": 24
  },
  {
    "brandID": "brand-6c08dd9110071630",
    "light": "assets/brands/brand-6c08dd9110071630.png",
    "dark": "assets/brands/brand-6c08dd9110071630.png",
    "size": 24
  },
  {
    "brandID": "brand-181187ba991ba4b4",
    "light": "assets/brands/brand-181187ba991ba4b4.png",
    "dark": "assets/brands/brand-181187ba991ba4b4.png",
    "size": 24
  },
  {
    "brandID": "brand-107242d376b660d8",
    "light": "assets/brands/brand-107242d376b660d8.png",
    "dark": "assets/brands/brand-107242d376b660d8.png",
    "size": 24
  },
  {
    "brandID": "brand-8295deb98137d4e8",
    "light": "assets/brands/brand-8295deb98137d4e8.png",
    "dark": "assets/brands/brand-8295deb98137d4e8.png",
    "size": 24
  },
  {
    "brandID": "brand-4c083db1c283fec1",
    "light": "assets/brands/brand-4c083db1c283fec1.png",
    "dark": "assets/brands/brand-4c083db1c283fec1.png",
    "size": 24
  },
  {
    "brandID": "brand-0370a62b904e4b47",
    "light": "assets/brands/brand-0370a62b904e4b47.png",
    "dark": "assets/brands/brand-0370a62b904e4b47.png",
    "size": 24
  },
  {
    "brandID": "brand-5038cd91fa8fbc26",
    "light": "assets/brands/brand-5038cd91fa8fbc26.png",
    "dark": "assets/brands/brand-5038cd91fa8fbc26.png",
    "size": 24
  },
  {
    "brandID": "brand-04127553b4fb06d0",
    "light": "assets/brands/safepal-dark.png",
    "dark": "assets/brands/safepal-light.png",
    "size": 20
  },
  {
    "brandID": "brand-5d95dad8e25d6e3a",
    "light": "assets/brands/brand-5d95dad8e25d6e3a.png",
    "dark": "assets/brands/brand-5d95dad8e25d6e3a.png",
    "size": 24
  },
  {
    "brandID": "brand-9b1e6040c2d209ea",
    "light": "assets/brands/brand-9b1e6040c2d209ea.png",
    "dark": "assets/brands/brand-9b1e6040c2d209ea.png",
    "size": 24
  },
  {
    "brandID": "brand-6ed8e486de8bb03b",
    "light": "assets/brands/brand-6ed8e486de8bb03b.png",
    "dark": "assets/brands/brand-6ed8e486de8bb03b.png",
    "size": 24
  },
  {
    "brandID": "brand-5262111f33e05963",
    "light": "assets/brands/brand-5262111f33e05963.png",
    "dark": "assets/brands/brand-5262111f33e05963.png",
    "size": 24
  },
  {
    "brandID": "brand-854377eb28f08346",
    "light": "assets/brands/brand-854377eb28f08346.png",
    "dark": "assets/brands/brand-854377eb28f08346.png",
    "size": 24
  },
  {
    "brandID": "brand-d1aff162effb746e",
    "light": "assets/brands/brand-d1aff162effb746e.png",
    "dark": "assets/brands/brand-d1aff162effb746e.png",
    "size": 24
  },
  {
    "brandID": "brand-bd3cba85ce4cde43",
    "light": "assets/brands/brand-bd3cba85ce4cde43.png",
    "dark": "assets/brands/brand-bd3cba85ce4cde43.png",
    "size": 24
  },
  {
    "brandID": "brand-66bd51ee0dbc4bca",
    "light": "assets/brands/brand-66bd51ee0dbc4bca.png",
    "dark": "assets/brands/brand-66bd51ee0dbc4bca.png",
    "size": 24
  },
  {
    "brandID": "brand-7085b91e3c52f69a",
    "light": "assets/brands/brand-7085b91e3c52f69a.png",
    "dark": "assets/brands/brand-7085b91e3c52f69a.png",
    "size": 24
  },
  {
    "brandID": "brand-02d927a049a259ac",
    "light": "assets/brands/brand-02d927a049a259ac.png",
    "dark": "assets/brands/brand-02d927a049a259ac.png",
    "size": 24
  },
  {
    "brandID": "brand-f2b81d85a1003c1d",
    "light": "assets/brands/brand-f2b81d85a1003c1d.png",
    "dark": "assets/brands/brand-f2b81d85a1003c1d.png",
    "size": 24
  },
  {
    "brandID": "brand-8411f5abb4c710b1",
    "light": "assets/brands/brand-8411f5abb4c710b1.png",
    "dark": "assets/brands/brand-8411f5abb4c710b1.png",
    "size": 24
  },
  {
    "brandID": "brand-3100f9d1060c22d0",
    "light": "assets/brands/brand-3100f9d1060c22d0.png",
    "dark": "assets/brands/brand-3100f9d1060c22d0.png",
    "size": 24
  },
  {
    "brandID": "brand-295c12597b1739a6",
    "light": "assets/brands/brand-295c12597b1739a6.png",
    "dark": "assets/brands/brand-295c12597b1739a6.png",
    "size": 24
  },
  {
    "brandID": "brand-b2039dc0b9fafb38",
    "light": "assets/brands/brand-b2039dc0b9fafb38.png",
    "dark": "assets/brands/brand-b2039dc0b9fafb38.png",
    "size": 24
  },
  {
    "brandID": "brand-42f3ac682ece1164",
    "light": "assets/brands/brand-42f3ac682ece1164.png",
    "dark": "assets/brands/brand-42f3ac682ece1164.png",
    "size": 24
  },
  {
    "brandID": "brand-8d38d3b6233f4781",
    "light": "assets/brands/brand-8d38d3b6233f4781.png",
    "dark": "assets/brands/brand-8d38d3b6233f4781.png",
    "size": 24
  },
  {
    "brandID": "brand-56e1a0723f1d4616",
    "light": "assets/brands/brand-56e1a0723f1d4616.png",
    "dark": "assets/brands/brand-56e1a0723f1d4616.png",
    "size": 24
  },
  {
    "brandID": "brand-2f27954b79f6b3c0",
    "light": "assets/brands/brand-2f27954b79f6b3c0.png",
    "dark": "assets/brands/brand-2f27954b79f6b3c0.png",
    "size": 24
  },
  {
    "brandID": "brand-5a602d15a5820f43",
    "light": "assets/brands/brand-5a602d15a5820f43.png",
    "dark": "assets/brands/brand-5a602d15a5820f43.png",
    "size": 24
  },
  {
    "brandID": "brand-3fc7e6c97a6988e4",
    "light": "assets/brands/brand-3fc7e6c97a6988e4.png",
    "dark": "assets/brands/brand-3fc7e6c97a6988e4.png",
    "size": 24
  },
  {
    "brandID": "brand-79ae270ddf6eb1bd",
    "light": "assets/brands/brand-79ae270ddf6eb1bd.png",
    "dark": "assets/brands/brand-79ae270ddf6eb1bd.png",
    "size": 24
  },
  {
    "brandID": "brand-d044fac5b926e628",
    "light": "assets/brands/brand-d044fac5b926e628.png",
    "dark": "assets/brands/brand-d044fac5b926e628.png",
    "size": 24
  },
  {
    "brandID": "brand-0e65394d692a2f12",
    "light": "assets/brands/brand-0e65394d692a2f12.png",
    "dark": "assets/brands/brand-0e65394d692a2f12.png",
    "size": 24
  },
  {
    "brandID": "brand-e89345d940a42dc0",
    "light": "assets/brands/brand-e89345d940a42dc0.png",
    "dark": "assets/brands/brand-e89345d940a42dc0.png",
    "size": 24
  },
  {
    "brandID": "brand-bd43c62d6ccc0ceb",
    "light": "assets/brands/brand-bd43c62d6ccc0ceb.png",
    "dark": "assets/brands/brand-bd43c62d6ccc0ceb.png",
    "size": 24
  },
  {
    "brandID": "brand-69ccf59b416bc5b3",
    "light": "assets/brands/brand-69ccf59b416bc5b3.png",
    "dark": "assets/brands/brand-69ccf59b416bc5b3.png",
    "size": 24
  },
  {
    "brandID": "brand-2e34fd6e4ef1a5d0",
    "light": "assets/brands/brand-2e34fd6e4ef1a5d0.png",
    "dark": "assets/brands/brand-2e34fd6e4ef1a5d0.png",
    "size": 24
  },
  {
    "brandID": "brand-37d401bc53ab48d6",
    "light": "assets/brands/brand-37d401bc53ab48d6.png",
    "dark": "assets/brands/brand-37d401bc53ab48d6.png",
    "size": 24
  },
  {
    "brandID": "brand-fd1696acc61502c7",
    "light": "assets/brands/brand-fd1696acc61502c7.png",
    "dark": "assets/brands/brand-fd1696acc61502c7.png",
    "size": 24
  },
  {
    "brandID": "brand-fe96a898b529366a",
    "light": "assets/brands/brand-fe96a898b529366a.png",
    "dark": "assets/brands/brand-fe96a898b529366a.png",
    "size": 24
  },
  {
    "brandID": "brand-05636ecd7a0644d4",
    "light": "assets/brands/brand-05636ecd7a0644d4.png",
    "dark": "assets/brands/brand-05636ecd7a0644d4.png",
    "size": 24
  },
  {
    "brandID": "brand-2543d920c5347ebb",
    "light": "assets/brands/brand-2543d920c5347ebb.png",
    "dark": "assets/brands/brand-2543d920c5347ebb.png",
    "size": 24
  },
  {
    "brandID": "brand-d05f6c8853d7fa56",
    "light": "assets/brands/brand-d05f6c8853d7fa56.png",
    "dark": "assets/brands/brand-d05f6c8853d7fa56.png",
    "size": 24
  },
  {
    "brandID": "brand-2c75c5f6caa8803c",
    "light": "assets/brands/brand-2c75c5f6caa8803c.png",
    "dark": "assets/brands/brand-2c75c5f6caa8803c.png",
    "size": 24
  },
  {
    "brandID": "brand-938600840aedcf57",
    "light": "assets/brands/brand-938600840aedcf57.png",
    "dark": "assets/brands/brand-938600840aedcf57.png",
    "size": 24
  },
  {
    "brandID": "brand-2b1bbe44e8af51d5",
    "light": "assets/brands/brand-2b1bbe44e8af51d5.png",
    "dark": "assets/brands/brand-2b1bbe44e8af51d5.png",
    "size": 24
  },
  {
    "brandID": "brand-7f073d54aeb1453a",
    "light": "assets/brands/brand-7f073d54aeb1453a.png",
    "dark": "assets/brands/brand-7f073d54aeb1453a.png",
    "size": 24
  },
  {
    "brandID": "brand-54a84b779870febc",
    "light": "assets/brands/brand-54a84b779870febc.png",
    "dark": "assets/brands/brand-54a84b779870febc.png",
    "size": 24
  },
  {
    "brandID": "brand-1fe317a3930a0a22",
    "light": "assets/brands/brand-1fe317a3930a0a22.png",
    "dark": "assets/brands/brand-1fe317a3930a0a22.png",
    "size": 24
  },
  {
    "brandID": "brand-a90a235139403c74",
    "light": "assets/brands/brand-a90a235139403c74.png",
    "dark": "assets/brands/brand-a90a235139403c74.png",
    "size": 24
  },
  {
    "brandID": "brand-14f963cdebc312f4",
    "light": "assets/brands/brand-14f963cdebc312f4.png",
    "dark": "assets/brands/brand-14f963cdebc312f4.png",
    "size": 24
  },
  {
    "brandID": "brand-8f5db3682475080c",
    "light": "assets/brands/brand-8f5db3682475080c.png",
    "dark": "assets/brands/brand-8f5db3682475080c.png",
    "size": 24
  },
  {
    "brandID": "brand-eb199c582b380999",
    "light": "assets/brands/brand-eb199c582b380999.png",
    "dark": "assets/brands/brand-eb199c582b380999.png",
    "size": 24
  },
  {
    "brandID": "brand-8ddefb0087b1484e",
    "light": "assets/brands/brand-8ddefb0087b1484e.png",
    "dark": "assets/brands/brand-8ddefb0087b1484e.png",
    "size": 24
  },
  {
    "brandID": "brand-7146bb9bfe2cc937",
    "light": "assets/brands/brand-7146bb9bfe2cc937.png",
    "dark": "assets/brands/brand-7146bb9bfe2cc937.png",
    "size": 24
  },
  {
    "brandID": "brand-b62d50d64dd85fef",
    "light": "assets/brands/brand-b62d50d64dd85fef.png",
    "dark": "assets/brands/brand-b62d50d64dd85fef.png",
    "size": 24
  },
  {
    "brandID": "brand-16887cb78fee70e6",
    "light": "assets/brands/brand-16887cb78fee70e6.png",
    "dark": "assets/brands/brand-16887cb78fee70e6.png",
    "size": 24
  },
  {
    "brandID": "brand-4beac98d6b970184",
    "light": "assets/brands/brand-4beac98d6b970184.png",
    "dark": "assets/brands/brand-4beac98d6b970184.png",
    "size": 24
  },
  {
    "brandID": "brand-3b7867056fbe15ef",
    "light": "assets/brands/brand-3b7867056fbe15ef.png",
    "dark": "assets/brands/brand-3b7867056fbe15ef.png",
    "size": 24
  },
  {
    "brandID": "brand-25ca826790387ee1",
    "light": "assets/brands/brand-25ca826790387ee1.png",
    "dark": "assets/brands/brand-25ca826790387ee1.png",
    "size": 24
  },
  {
    "brandID": "brand-2617ad5916dfd467",
    "light": "assets/brands/brand-2617ad5916dfd467.png",
    "dark": "assets/brands/brand-2617ad5916dfd467.png",
    "size": 24
  },
  {
    "brandID": "brand-cdb435a9080fa7f5",
    "light": "assets/brands/brand-cdb435a9080fa7f5.png",
    "dark": "assets/brands/brand-cdb435a9080fa7f5.png",
    "size": 24
  },
  {
    "brandID": "brand-3e94c1e85f8c8484",
    "light": "assets/brands/brand-3e94c1e85f8c8484.png",
    "dark": "assets/brands/brand-3e94c1e85f8c8484.png",
    "size": 24
  },
  {
    "brandID": "brand-e98a013e5e2e395d",
    "light": "assets/brands/brand-e98a013e5e2e395d.png",
    "dark": "assets/brands/brand-e98a013e5e2e395d.png",
    "size": 24
  },
  {
    "brandID": "brand-b2d4516e41c0e2a3",
    "light": "assets/brands/brand-b2d4516e41c0e2a3.png",
    "dark": "assets/brands/brand-b2d4516e41c0e2a3.png",
    "size": 24
  },
  {
    "brandID": "brand-fea67f0ffe22d188",
    "light": "assets/brands/brand-fea67f0ffe22d188.png",
    "dark": "assets/brands/brand-fea67f0ffe22d188.png",
    "size": 24
  },
  {
    "brandID": "brand-1e612ddc8a331a49",
    "light": "assets/brands/brand-1e612ddc8a331a49.png",
    "dark": "assets/brands/brand-1e612ddc8a331a49.png",
    "size": 24
  },
  {
    "brandID": "brand-bc89b6dc4d866186",
    "light": "assets/brands/brand-bc89b6dc4d866186.png",
    "dark": "assets/brands/brand-bc89b6dc4d866186.png",
    "size": 24
  },
  {
    "brandID": "brand-c5f36f3aadd42d15",
    "light": "assets/brands/brand-c5f36f3aadd42d15.png",
    "dark": "assets/brands/brand-c5f36f3aadd42d15.png",
    "size": 24
  },
  {
    "brandID": "brand-a4ad4d4d6635467d",
    "light": "assets/brands/brand-a4ad4d4d6635467d.png",
    "dark": "assets/brands/brand-a4ad4d4d6635467d.png",
    "size": 24
  },
  {
    "brandID": "brand-4f241cd4f73aecc5",
    "light": "assets/brands/brand-4f241cd4f73aecc5.png",
    "dark": "assets/brands/brand-4f241cd4f73aecc5.png",
    "size": 24
  },
  {
    "brandID": "brand-56f0d73541e82c3f",
    "light": "assets/brands/brand-56f0d73541e82c3f.png",
    "dark": "assets/brands/brand-56f0d73541e82c3f.png",
    "size": 24
  },
  {
    "brandID": "brand-133a62a291400c7c",
    "light": "assets/brands/brand-133a62a291400c7c.png",
    "dark": "assets/brands/brand-133a62a291400c7c.png",
    "size": 24
  },
  {
    "brandID": "brand-5184c5ccab1a6c6f",
    "light": "assets/brands/brand-5184c5ccab1a6c6f.png",
    "dark": "assets/brands/brand-5184c5ccab1a6c6f.png",
    "size": 24
  },
  {
    "brandID": "brand-e3e0f227975425a5",
    "light": "assets/brands/brand-e3e0f227975425a5.png",
    "dark": "assets/brands/brand-e3e0f227975425a5.png",
    "size": 24
  },
  {
    "brandID": "brand-2683a2acfc9299dd",
    "light": "assets/brands/brand-2683a2acfc9299dd.png",
    "dark": "assets/brands/brand-2683a2acfc9299dd.png",
    "size": 24
  },
  {
    "brandID": "brand-2dc2b7b140424040",
    "light": "assets/brands/brand-2dc2b7b140424040.png",
    "dark": "assets/brands/brand-2dc2b7b140424040.png",
    "size": 24
  },
  {
    "brandID": "brand-3ee386b0fe612350",
    "light": "assets/brands/brand-3ee386b0fe612350.png",
    "dark": "assets/brands/brand-3ee386b0fe612350.png",
    "size": 24
  },
  {
    "brandID": "brand-19b8a3e7741676b0",
    "light": "assets/brands/brand-19b8a3e7741676b0.png",
    "dark": "assets/brands/brand-19b8a3e7741676b0.png",
    "size": 24
  },
  {
    "brandID": "brand-480ac83de932e557",
    "light": "assets/brands/brand-480ac83de932e557.png",
    "dark": "assets/brands/brand-480ac83de932e557.png",
    "size": 24
  },
  {
    "brandID": "brand-eed88ae172047e11",
    "light": "assets/brands/brand-eed88ae172047e11.png",
    "dark": "assets/brands/brand-eed88ae172047e11.png",
    "size": 24
  },
  {
    "brandID": "brand-1ba52ccc50f72660",
    "light": "assets/brands/brand-1ba52ccc50f72660.png",
    "dark": "assets/brands/brand-1ba52ccc50f72660.png",
    "size": 24
  },
  {
    "brandID": "brand-62ac52ca4dc4caa8",
    "light": "assets/brands/brand-62ac52ca4dc4caa8.png",
    "dark": "assets/brands/brand-62ac52ca4dc4caa8.png",
    "size": 24
  },
  {
    "brandID": "brand-a3c4266d9345f11f",
    "light": "assets/brands/brand-a3c4266d9345f11f.png",
    "dark": "assets/brands/brand-a3c4266d9345f11f.png",
    "size": 24
  },
  {
    "brandID": "brand-019d5d6f23bf9446",
    "light": "assets/brands/brand-019d5d6f23bf9446.png",
    "dark": "assets/brands/brand-019d5d6f23bf9446.png",
    "size": 24
  },
  {
    "brandID": "brand-d3c20bd565303d39",
    "light": "assets/brands/brand-d3c20bd565303d39.png",
    "dark": "assets/brands/brand-d3c20bd565303d39.png",
    "size": 24
  },
  {
    "brandID": "brand-96ea8fc8b10f3a01",
    "light": "assets/brands/brand-96ea8fc8b10f3a01.png",
    "dark": "assets/brands/brand-96ea8fc8b10f3a01.png",
    "size": 24
  },
  {
    "brandID": "brand-34c667101c639044",
    "light": "assets/brands/brand-34c667101c639044.png",
    "dark": "assets/brands/brand-34c667101c639044.png",
    "size": 24
  },
  {
    "brandID": "brand-7117fa8d72fb99b9",
    "light": "assets/brands/brand-7117fa8d72fb99b9.png",
    "dark": "assets/brands/brand-7117fa8d72fb99b9.png",
    "size": 24
  },
  {
    "brandID": "brand-b76d5350028dfa74",
    "light": "assets/brands/brand-b76d5350028dfa74.png",
    "dark": "assets/brands/brand-b76d5350028dfa74.png",
    "size": 24
  },
  {
    "brandID": "brand-7b56d9ac5b8f2477",
    "light": "assets/brands/brand-7b56d9ac5b8f2477.png",
    "dark": "assets/brands/brand-7b56d9ac5b8f2477.png",
    "size": 24
  },
  {
    "brandID": "brand-9aff75ca94b86763",
    "light": "assets/brands/brand-9aff75ca94b86763.png",
    "dark": "assets/brands/brand-9aff75ca94b86763.png",
    "size": 24
  },
  {
    "brandID": "brand-1403a55e2eeebf16",
    "light": "assets/brands/brand-1403a55e2eeebf16.png",
    "dark": "assets/brands/brand-1403a55e2eeebf16.png",
    "size": 24
  },
  {
    "brandID": "brand-afc476e0e32e6909",
    "light": "assets/brands/brand-afc476e0e32e6909.png",
    "dark": "assets/brands/brand-afc476e0e32e6909.png",
    "size": 24
  },
  {
    "brandID": "brand-c92ea5ccbde2fe28",
    "light": "assets/brands/brand-c92ea5ccbde2fe28.png",
    "dark": "assets/brands/brand-c92ea5ccbde2fe28.png",
    "size": 24
  },
  {
    "brandID": "brand-b25d4954af714fbc",
    "light": "assets/brands/brand-b25d4954af714fbc.png",
    "dark": "assets/brands/brand-b25d4954af714fbc.png",
    "size": 24
  },
  {
    "brandID": "brand-47baf3a38c274d70",
    "light": "assets/brands/brand-47baf3a38c274d70.png",
    "dark": "assets/brands/brand-47baf3a38c274d70.png",
    "size": 24
  },
  {
    "brandID": "brand-dcb1448b6d5bef08",
    "light": "assets/brands/brand-dcb1448b6d5bef08.png",
    "dark": "assets/brands/brand-dcb1448b6d5bef08.png",
    "size": 24
  },
  {
    "brandID": "brand-3b00b32d64af3c23",
    "light": "assets/brands/brand-3b00b32d64af3c23.png",
    "dark": "assets/brands/brand-3b00b32d64af3c23.png",
    "size": 24
  },
  {
    "brandID": "brand-e621165ce13e0ef5",
    "light": "assets/brands/brand-e621165ce13e0ef5.png",
    "dark": "assets/brands/brand-e621165ce13e0ef5.png",
    "size": 24
  },
  {
    "brandID": "brand-c642fdf45b2882bc",
    "light": "assets/brands/brand-c642fdf45b2882bc.png",
    "dark": "assets/brands/brand-c642fdf45b2882bc.png",
    "size": 24
  },
  {
    "brandID": "brand-7c3f048af591b972",
    "light": "assets/brands/brand-7c3f048af591b972.png",
    "dark": "assets/brands/brand-7c3f048af591b972.png",
    "size": 24
  },
  {
    "brandID": "brand-da3a2406bd90809a",
    "light": "assets/brands/brand-da3a2406bd90809a.png",
    "dark": "assets/brands/brand-da3a2406bd90809a.png",
    "size": 24
  },
  {
    "brandID": "brand-d1cac591c672f912",
    "light": "assets/brands/brand-d1cac591c672f912.png",
    "dark": "assets/brands/brand-d1cac591c672f912.png",
    "size": 24
  },
  {
    "brandID": "brand-d8d384c4e02cb94e",
    "light": "assets/brands/brand-d8d384c4e02cb94e.png",
    "dark": "assets/brands/brand-d8d384c4e02cb94e.png",
    "size": 24
  },
  {
    "brandID": "brand-4997d093758bf1ad",
    "light": "assets/brands/brand-4997d093758bf1ad.png",
    "dark": "assets/brands/brand-4997d093758bf1ad.png",
    "size": 24
  },
  {
    "brandID": "brand-6ba934928aa14ad5",
    "light": "assets/brands/brand-6ba934928aa14ad5.png",
    "dark": "assets/brands/brand-6ba934928aa14ad5.png",
    "size": 24
  },
  {
    "brandID": "brand-392b3b34d7f49ebb",
    "light": "assets/brands/brand-392b3b34d7f49ebb.png",
    "dark": "assets/brands/brand-392b3b34d7f49ebb.png",
    "size": 24
  },
  {
    "brandID": "brand-785ba7c5543bf611",
    "light": "assets/brands/brand-785ba7c5543bf611.png",
    "dark": "assets/brands/brand-785ba7c5543bf611.png",
    "size": 24
  },
  {
    "brandID": "brand-a014c1c4bf844591",
    "light": "assets/brands/brand-a014c1c4bf844591.png",
    "dark": "assets/brands/brand-a014c1c4bf844591.png",
    "size": 24
  },
  {
    "brandID": "brand-12841e813fb9e429",
    "light": "assets/brands/brand-12841e813fb9e429.png",
    "dark": "assets/brands/brand-12841e813fb9e429.png",
    "size": 24
  },
  {
    "brandID": "brand-6ee83476fe7d41d0",
    "light": "assets/brands/brand-6ee83476fe7d41d0.png",
    "dark": "assets/brands/brand-6ee83476fe7d41d0.png",
    "size": 24
  },
  {
    "brandID": "brand-7df999bb5bbab0b3",
    "light": "assets/brands/brand-7df999bb5bbab0b3.png",
    "dark": "assets/brands/brand-7df999bb5bbab0b3.png",
    "size": 24
  },
  {
    "brandID": "brand-2e4b5921ffde84c2",
    "light": "assets/brands/brand-2e4b5921ffde84c2.png",
    "dark": "assets/brands/brand-2e4b5921ffde84c2.png",
    "size": 24
  },
  {
    "brandID": "brand-8e9c94329ae8b1a6",
    "light": "assets/brands/brand-8e9c94329ae8b1a6.png",
    "dark": "assets/brands/brand-8e9c94329ae8b1a6.png",
    "size": 24
  },
  {
    "brandID": "brand-02e75c98a053e228",
    "light": "assets/brands/brand-02e75c98a053e228.png",
    "dark": "assets/brands/brand-02e75c98a053e228.png",
    "size": 24
  },
  {
    "brandID": "brand-764d4c6d3e32933a",
    "light": "assets/brands/brand-764d4c6d3e32933a.png",
    "dark": "assets/brands/brand-764d4c6d3e32933a.png",
    "size": 24
  },
  {
    "brandID": "brand-bc031f81734b4d02",
    "light": "assets/brands/brand-bc031f81734b4d02.png",
    "dark": "assets/brands/brand-bc031f81734b4d02.png",
    "size": 24
  },
  {
    "brandID": "brand-4a9e4a5e58be4df9",
    "light": "assets/brands/brand-4a9e4a5e58be4df9.png",
    "dark": "assets/brands/brand-4a9e4a5e58be4df9.png",
    "size": 24
  },
  {
    "brandID": "brand-fb54e0f95e21a991",
    "light": "assets/brands/brand-fb54e0f95e21a991.png",
    "dark": "assets/brands/brand-fb54e0f95e21a991.png",
    "size": 24
  },
  {
    "brandID": "brand-f7b39b2d1a2a93b8",
    "light": "assets/brands/brand-f7b39b2d1a2a93b8.png",
    "dark": "assets/brands/brand-f7b39b2d1a2a93b8.png",
    "size": 24
  },
  {
    "brandID": "brand-61e19208df06395c",
    "light": "assets/brands/brand-61e19208df06395c.png",
    "dark": "assets/brands/brand-61e19208df06395c.png",
    "size": 24
  },
  {
    "brandID": "brand-df2f91012c221bc2",
    "light": "assets/brands/brand-df2f91012c221bc2.png",
    "dark": "assets/brands/brand-df2f91012c221bc2.png",
    "size": 24
  },
  {
    "brandID": "brand-39d2409ac58a1a63",
    "light": "assets/brands/brand-39d2409ac58a1a63.png",
    "dark": "assets/brands/brand-39d2409ac58a1a63.png",
    "size": 24
  },
  {
    "brandID": "brand-81f5470f1e04014b",
    "light": "assets/brands/brand-81f5470f1e04014b.png",
    "dark": "assets/brands/brand-81f5470f1e04014b.png",
    "size": 24
  },
  {
    "brandID": "brand-9b1a14126585226c",
    "light": "assets/brands/brand-9b1a14126585226c.png",
    "dark": "assets/brands/brand-9b1a14126585226c.png",
    "size": 24
  },
  {
    "brandID": "brand-e8c0eab4994ba898",
    "light": "assets/brands/brand-e8c0eab4994ba898.png",
    "dark": "assets/brands/brand-e8c0eab4994ba898.png",
    "size": 24
  },
  {
    "brandID": "brand-d42c2d80abf827fe",
    "light": "assets/brands/brand-d42c2d80abf827fe.png",
    "dark": "assets/brands/brand-d42c2d80abf827fe.png",
    "size": 24
  },
  {
    "brandID": "brand-a6bbbb95cddbd970",
    "light": "assets/brands/brand-a6bbbb95cddbd970.png",
    "dark": "assets/brands/brand-a6bbbb95cddbd970.png",
    "size": 24
  },
  {
    "brandID": "brand-ff98d8a1e29266f6",
    "light": "assets/brands/brand-ff98d8a1e29266f6.png",
    "dark": "assets/brands/brand-ff98d8a1e29266f6.png",
    "size": 24
  },
  {
    "brandID": "brand-492cae23f6e556f3",
    "light": "assets/brands/brand-492cae23f6e556f3.png",
    "dark": "assets/brands/brand-492cae23f6e556f3.png",
    "size": 24
  },
  {
    "brandID": "brand-f9191531404c4016",
    "light": "assets/brands/brand-f9191531404c4016.png",
    "dark": "assets/brands/brand-f9191531404c4016.png",
    "size": 24
  },
  {
    "brandID": "brand-68edc75c015e2e10",
    "light": "assets/brands/brand-68edc75c015e2e10.png",
    "dark": "assets/brands/brand-68edc75c015e2e10.png",
    "size": 24
  },
  {
    "brandID": "brand-8db02fc979fdbbb6",
    "light": "assets/brands/brand-8db02fc979fdbbb6.png",
    "dark": "assets/brands/brand-8db02fc979fdbbb6.png",
    "size": 24
  },
  {
    "brandID": "brand-e16fc821f34228d1",
    "light": "assets/brands/brand-e16fc821f34228d1.png",
    "dark": "assets/brands/brand-e16fc821f34228d1.png",
    "size": 24
  },
  {
    "brandID": "brand-a7baed72c308ce88",
    "light": "assets/brands/brand-a7baed72c308ce88.png",
    "dark": "assets/brands/brand-a7baed72c308ce88.png",
    "size": 24
  }
]
