// SPDX-FileCopyrightText: 2026 MaroonYS
// SPDX-License-Identifier: LicenseRef-Due-Manager-Personal-Use-1.0
// See LICENSE and NOTICE.md. All rights reserved, subject to their exceptions.
// Generated by tools/build_runtime_brand_catalog.ts. Names are not artwork licenses.

export interface BrandDefinition { id: string; name: string; group: string; aliases: string[] }
export const BRAND_CATALOG: BrandDefinition[] = [
  {
    "id": "brand-cf480cbb7a87b6d3",
    "name": "Capital One",
    "group": "美国银行与信用卡",
    "aliases": [
      "Capital One"
    ]
  },
  {
    "id": "brand-1ae6e6416a7ad654",
    "name": "Chase",
    "group": "美国银行与信用卡",
    "aliases": []
  },
  {
    "id": "brand-952395274255063a",
    "name": "Bank of America",
    "group": "美国银行与信用卡",
    "aliases": [
      "Bank of America"
    ]
  },
  {
    "id": "brand-1a34654a0c199abf",
    "name": "Wells Fargo",
    "group": "美国银行与信用卡",
    "aliases": [
      "Wells Fargo"
    ]
  },
  {
    "id": "brand-e9591c52923895e2",
    "name": "Citi",
    "group": "美国银行与信用卡",
    "aliases": [
      "Citi"
    ]
  },
  {
    "id": "brand-e2c258181616411e",
    "name": "American Express",
    "group": "美国银行与信用卡",
    "aliases": [
      "American Express"
    ]
  },
  {
    "id": "brand-aa2c2fdc65c38b9f",
    "name": "U.S. Bank",
    "group": "美国银行与信用卡",
    "aliases": [
      "U.S. Bank"
    ]
  },
  {
    "id": "brand-b21b93a4701fc767",
    "name": "SoFi",
    "group": "美国银行与信用卡",
    "aliases": [
      "SoFi"
    ]
  },
  {
    "id": "brand-4cc4e63ced381bd7",
    "name": "Chime",
    "group": "美国银行与信用卡",
    "aliases": []
  },
  {
    "id": "brand-063fa0c03a82346c",
    "name": "Fifth Third",
    "group": "美国银行与信用卡",
    "aliases": [
      "Fifth Third"
    ]
  },
  {
    "id": "brand-9e33f12992cab994",
    "name": "中国农业银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "中国农业银行"
    ]
  },
  {
    "id": "brand-e5ea46ebc1c7fa36",
    "name": "中国工商银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "中国工商银行"
    ]
  },
  {
    "id": "brand-e0f8aebbf712178d",
    "name": "中国建设银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "中国建设银行"
    ]
  },
  {
    "id": "brand-caf76992859b35e9",
    "name": "中国银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "中国银行"
    ]
  },
  {
    "id": "brand-3e87bc0a97f15971",
    "name": "招商银行／掌上生活",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "招商银行",
      "掌上生活"
    ]
  },
  {
    "id": "brand-1de9de20ec4771e1",
    "name": "交通银行／买单吧",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "交通银行",
      "买单吧"
    ]
  },
  {
    "id": "brand-f112198ca6d5bcfe",
    "name": "邮储银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "邮储银行"
    ]
  },
  {
    "id": "brand-d27f28e288e77b81",
    "name": "平安口袋银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "平安口袋银行"
    ]
  },
  {
    "id": "brand-d26d781218719c33",
    "name": "中信银行／动卡空间",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "中信银行",
      "动卡空间"
    ]
  },
  {
    "id": "brand-65886f285b393964",
    "name": "兴业银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "兴业银行"
    ]
  },
  {
    "id": "brand-057fd3120b08c322",
    "name": "浦发银行／浦大喜奔",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "浦发银行",
      "浦大喜奔"
    ]
  },
  {
    "id": "brand-d177ef7f1d911e4d",
    "name": "民生银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "民生银行"
    ]
  },
  {
    "id": "brand-b724ddcec8bc9cba",
    "name": "光大银行",
    "group": "中国大陆银行与信用卡",
    "aliases": [
      "光大银行"
    ]
  },
  {
    "id": "brand-5bd43e1a5086e677",
    "name": "中银香港／BoC Pay+",
    "group": "香港银行与信用卡",
    "aliases": [
      "中银香港",
      "BoC Pay+"
    ]
  },
  {
    "id": "brand-0b0594c9164b3972",
    "name": "汇丰香港／Reward+",
    "group": "香港银行与信用卡",
    "aliases": [
      "汇丰香港",
      "Reward+"
    ]
  },
  {
    "id": "brand-0f1b3c1321902d3e",
    "name": "恒生银行",
    "group": "香港银行与信用卡",
    "aliases": [
      "恒生银行"
    ]
  },
  {
    "id": "brand-91a66b21430fc7f3",
    "name": "渣打香港",
    "group": "香港银行与信用卡",
    "aliases": [
      "渣打香港"
    ]
  },
  {
    "id": "brand-c1974cbeaeaba234",
    "name": "Mox",
    "group": "香港银行与信用卡",
    "aliases": [
      "Mox"
    ]
  },
  {
    "id": "brand-b56633823acf3bba",
    "name": "ZA Bank",
    "group": "香港银行与信用卡",
    "aliases": [
      "ZA Bank"
    ]
  },
  {
    "id": "brand-53315e6525e54a82",
    "name": "DBS Card+ HK",
    "group": "香港银行与信用卡",
    "aliases": [
      "DBS Card+ HK"
    ]
  },
  {
    "id": "brand-c9804bab8f7234ae",
    "name": "东亚银行",
    "group": "香港银行与信用卡",
    "aliases": [
      "东亚银行"
    ]
  },
  {
    "id": "brand-08320ff72bfca8c2",
    "name": "建行港澳",
    "group": "香港银行与信用卡",
    "aliases": [
      "建行港澳"
    ]
  },
  {
    "id": "brand-14539267d83df9ba",
    "name": "Amex Hong Kong",
    "group": "香港银行与信用卡",
    "aliases": [
      "Amex Hong Kong"
    ]
  },
  {
    "id": "brand-824e367b5c775341",
    "name": "AEON HK",
    "group": "香港银行与信用卡",
    "aliases": [
      "AEON HK"
    ]
  },
  {
    "id": "brand-476be3b21a3f22f1",
    "name": "Lloyds",
    "group": "英国银行与信用卡",
    "aliases": [
      "Lloyds"
    ]
  },
  {
    "id": "brand-67831a00b4c103ff",
    "name": "Monzo",
    "group": "英国银行与信用卡",
    "aliases": [
      "Monzo"
    ]
  },
  {
    "id": "brand-511722345a0668f6",
    "name": "NatWest",
    "group": "英国银行与信用卡",
    "aliases": [
      "NatWest"
    ]
  },
  {
    "id": "brand-5aed45c196178dc6",
    "name": "Nationwide",
    "group": "英国银行与信用卡",
    "aliases": []
  },
  {
    "id": "brand-73a7c5c1df6eb4ce",
    "name": "Santander UK",
    "group": "英国银行与信用卡",
    "aliases": [
      "Santander UK"
    ]
  },
  {
    "id": "brand-07500f3dc48a89e4",
    "name": "Barclays／Barclaycard",
    "group": "英国银行与信用卡",
    "aliases": [
      "Barclays",
      "Barclaycard"
    ]
  },
  {
    "id": "brand-1933d4a79708d932",
    "name": "Starling",
    "group": "英国银行与信用卡",
    "aliases": []
  },
  {
    "id": "brand-b12733a5d63d7501",
    "name": "HSBC UK",
    "group": "英国银行与信用卡",
    "aliases": [
      "HSBC UK"
    ]
  },
  {
    "id": "brand-9a4230bbe97192a3",
    "name": "Capital One UK",
    "group": "英国银行与信用卡",
    "aliases": [
      "Capital One UK"
    ]
  },
  {
    "id": "brand-06a29a2f2e44bf79",
    "name": "Chase UK",
    "group": "英国银行与信用卡",
    "aliases": [
      "Chase UK"
    ]
  },
  {
    "id": "brand-b3b438c24d962a0f",
    "name": "Zopa",
    "group": "英国银行与信用卡",
    "aliases": [
      "Zopa"
    ]
  },
  {
    "id": "brand-b75732aa0f91e735",
    "name": "Halifax",
    "group": "英国银行与信用卡",
    "aliases": [
      "Halifax"
    ]
  },
  {
    "id": "brand-d12e6a419c206aea",
    "name": "Amex UK",
    "group": "英国银行与信用卡",
    "aliases": [
      "Amex UK"
    ]
  },
  {
    "id": "brand-ab8a4f6bb84d161b",
    "name": "PayPal",
    "group": "支付与汇款",
    "aliases": [
      "PayPal"
    ]
  },
  {
    "id": "brand-2105f7da1289e2d2",
    "name": "Cash App",
    "group": "支付与汇款",
    "aliases": [
      "Cash App"
    ]
  },
  {
    "id": "brand-a1593ecc5a13b7a0",
    "name": "Venmo",
    "group": "支付与汇款",
    "aliases": [
      "Venmo"
    ]
  },
  {
    "id": "brand-a2e779358d0d0fdf",
    "name": "Klarna",
    "group": "支付与汇款",
    "aliases": [
      "Klarna"
    ]
  },
  {
    "id": "brand-dd53271a2e067540",
    "name": "Revolut",
    "group": "支付与汇款",
    "aliases": [
      "Revolut"
    ]
  },
  {
    "id": "brand-e3fcf621116d3fe8",
    "name": "Wise",
    "group": "支付与汇款",
    "aliases": []
  },
  {
    "id": "brand-276a8bc458036a1a",
    "name": "支付宝",
    "group": "支付与汇款",
    "aliases": [
      "支付宝"
    ]
  },
  {
    "id": "brand-a01544d8fc145a8a",
    "name": "AlipayHK",
    "group": "支付与汇款",
    "aliases": [
      "AlipayHK"
    ]
  },
  {
    "id": "brand-d8a403a5d9abf615",
    "name": "八达通",
    "group": "支付与汇款",
    "aliases": [
      "八达通"
    ]
  },
  {
    "id": "brand-6419de732fece5d6",
    "name": "云闪付",
    "group": "支付与汇款",
    "aliases": [
      "云闪付"
    ]
  },
  {
    "id": "brand-0103f5d08eede1fb",
    "name": "PayMe",
    "group": "支付与汇款",
    "aliases": [
      "PayMe"
    ]
  },
  {
    "id": "brand-41c8b2ad4b7c7387",
    "name": "Remitly",
    "group": "支付与汇款",
    "aliases": [
      "Remitly"
    ]
  },
  {
    "id": "brand-52b22789c4c6e72b",
    "name": "Credit Karma",
    "group": "保险、信用与投资记录",
    "aliases": [
      "Credit Karma"
    ]
  },
  {
    "id": "brand-14eba0693bf48744",
    "name": "Experian US",
    "group": "保险、信用与投资记录",
    "aliases": [
      "Experian US"
    ]
  },
  {
    "id": "brand-11f3b69f9934166e",
    "name": "Experian UK",
    "group": "保险、信用与投资记录",
    "aliases": [
      "Experian UK"
    ]
  },
  {
    "id": "brand-0cfc3bb8500974c3",
    "name": "环联香港",
    "group": "保险、信用与投资记录",
    "aliases": [
      "环联香港"
    ]
  },
  {
    "id": "brand-95a4f01c0350d730",
    "name": "ClearScore",
    "group": "保险、信用与投资记录",
    "aliases": [
      "ClearScore"
    ]
  },
  {
    "id": "brand-ab43fc6eec59a19c",
    "name": "GEICO",
    "group": "保险、信用与投资记录",
    "aliases": [
      "GEICO"
    ]
  },
  {
    "id": "brand-c21bea0c6d590524",
    "name": "Progressive",
    "group": "保险、信用与投资记录",
    "aliases": [
      "Progressive"
    ]
  },
  {
    "id": "brand-66519047f5733551",
    "name": "State Farm",
    "group": "保险、信用与投资记录",
    "aliases": [
      "State Farm"
    ]
  },
  {
    "id": "brand-839b21c9cdc163c9",
    "name": "AIA HK",
    "group": "保险、信用与投资记录",
    "aliases": [
      "AIA HK"
    ]
  },
  {
    "id": "brand-ef1dcffbcfe38fef",
    "name": "AXA HK",
    "group": "保险、信用与投资记录",
    "aliases": [
      "AXA HK"
    ]
  },
  {
    "id": "brand-dfb80b004c96aa54",
    "name": "中国人寿",
    "group": "保险、信用与投资记录",
    "aliases": [
      "中国人寿"
    ]
  },
  {
    "id": "brand-320183649dde9491",
    "name": "中国人保",
    "group": "保险、信用与投资记录",
    "aliases": [
      "中国人保"
    ]
  },
  {
    "id": "brand-8da288304fae9a78",
    "name": "TradingView",
    "group": "保险、信用与投资记录",
    "aliases": [
      "TradingView"
    ]
  },
  {
    "id": "brand-3adf3250d46ff48f",
    "name": "富途牛牛",
    "group": "保险、信用与投资记录",
    "aliases": [
      "富途牛牛"
    ]
  },
  {
    "id": "brand-89b531787b023e79",
    "name": "IBKR",
    "group": "保险、信用与投资记录",
    "aliases": [
      "IBKR"
    ]
  },
  {
    "id": "brand-50a4122943273ad2",
    "name": "ChatGPT",
    "group": "AI 与数字订阅",
    "aliases": [
      "ChatGPT"
    ]
  },
  {
    "id": "brand-0615570f9ea13694",
    "name": "Claude",
    "group": "AI 与数字订阅",
    "aliases": []
  },
  {
    "id": "brand-063b734802746476",
    "name": "Google Gemini",
    "group": "AI 与数字订阅",
    "aliases": [
      "Google Gemini"
    ]
  },
  {
    "id": "brand-dca61d32363b091b",
    "name": "Grok",
    "group": "AI 与数字订阅",
    "aliases": [
      "Grok"
    ]
  },
  {
    "id": "brand-0648d2111ec0ca3d",
    "name": "DeepSeek",
    "group": "AI 与数字订阅",
    "aliases": [
      "DeepSeek"
    ]
  },
  {
    "id": "brand-f64660efbe61dd28",
    "name": "豆包",
    "group": "AI 与数字订阅",
    "aliases": []
  },
  {
    "id": "brand-db2d53fb1c9cf5fb",
    "name": "千问",
    "group": "AI 与数字订阅",
    "aliases": []
  },
  {
    "id": "brand-83f10a44727fc929",
    "name": "Kimi",
    "group": "AI 与数字订阅",
    "aliases": [
      "Kimi"
    ]
  },
  {
    "id": "brand-f394cc2a6da7dfd6",
    "name": "Perplexity",
    "group": "AI 与数字订阅",
    "aliases": [
      "Perplexity"
    ]
  },
  {
    "id": "brand-f09f149fa26808f8",
    "name": "Netflix",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Netflix"
    ]
  },
  {
    "id": "brand-02dc2a9874362dcb",
    "name": "Disney+",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Disney+"
    ]
  },
  {
    "id": "brand-681515c24531ca81",
    "name": "Prime Video",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Prime Video"
    ]
  },
  {
    "id": "brand-d3b7d7dd5caec996",
    "name": "HBO Max",
    "group": "视频与娱乐订阅",
    "aliases": [
      "HBO Max"
    ]
  },
  {
    "id": "brand-61f2c2a36de1f845",
    "name": "Hulu",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Hulu"
    ]
  },
  {
    "id": "brand-69e77a2d45ecb210",
    "name": "Peacock",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Peacock"
    ]
  },
  {
    "id": "brand-20ddfb33ebb13fd7",
    "name": "Paramount+",
    "group": "视频与娱乐订阅",
    "aliases": [
      "Paramount+"
    ]
  },
  {
    "id": "brand-590a5961464ddf6e",
    "name": "腾讯视频",
    "group": "视频与娱乐订阅",
    "aliases": [
      "腾讯视频"
    ]
  },
  {
    "id": "brand-67a67fc05f47b36e",
    "name": "爱奇艺",
    "group": "视频与娱乐订阅",
    "aliases": [
      "爱奇艺"
    ]
  },
  {
    "id": "brand-d50d4c56ce50ac9d",
    "name": "优酷",
    "group": "视频与娱乐订阅",
    "aliases": []
  },
  {
    "id": "brand-cfc3d445066f6e83",
    "name": "哔哩哔哩",
    "group": "视频与娱乐订阅",
    "aliases": [
      "哔哩哔哩"
    ]
  },
  {
    "id": "brand-7005c0064bda4edb",
    "name": "Spotify",
    "group": "音乐与音频",
    "aliases": [
      "Spotify"
    ]
  },
  {
    "id": "brand-6921a7cac539977d",
    "name": "YouTube Music",
    "group": "音乐与音频",
    "aliases": [
      "YouTube Music"
    ]
  },
  {
    "id": "brand-3ef42060a2e523ab",
    "name": "QQ音乐",
    "group": "音乐与音频",
    "aliases": [
      "QQ音乐"
    ]
  },
  {
    "id": "brand-4a366fb92e537bad",
    "name": "网易云音乐",
    "group": "音乐与音频",
    "aliases": [
      "网易云音乐"
    ]
  },
  {
    "id": "brand-7d0e8317588d3aec",
    "name": "酷狗音乐",
    "group": "音乐与音频",
    "aliases": [
      "酷狗音乐"
    ]
  },
  {
    "id": "brand-f8cff81f622364ff",
    "name": "汽水音乐",
    "group": "音乐与音频",
    "aliases": [
      "汽水音乐"
    ]
  },
  {
    "id": "brand-8506b11e2d839545",
    "name": "SoundCloud",
    "group": "音乐与音频",
    "aliases": [
      "SoundCloud"
    ]
  },
  {
    "id": "brand-0f622ac0d0500ae8",
    "name": "TIDAL",
    "group": "音乐与音频",
    "aliases": [
      "TIDAL"
    ]
  },
  {
    "id": "brand-4c57d8f0e66cbc66",
    "name": "Suno",
    "group": "音乐与音频",
    "aliases": []
  },
  {
    "id": "brand-a7b52b269a23c025",
    "name": "Microsoft Teams",
    "group": "办公与效率",
    "aliases": [
      "Microsoft Teams"
    ]
  },
  {
    "id": "brand-509c517ede79fef0",
    "name": "Zoom",
    "group": "办公与效率",
    "aliases": [
      "Zoom"
    ]
  },
  {
    "id": "brand-f3943a7b368154d1",
    "name": "企业微信",
    "group": "办公与效率",
    "aliases": [
      "企业微信"
    ]
  },
  {
    "id": "brand-27389885c97c4ab1",
    "name": "钉钉",
    "group": "办公与效率",
    "aliases": []
  },
  {
    "id": "brand-7e4419d1de251094",
    "name": "飞书",
    "group": "办公与效率",
    "aliases": []
  },
  {
    "id": "brand-b27fb38ba323745c",
    "name": "Slack",
    "group": "办公与效率",
    "aliases": [
      "Slack"
    ]
  },
  {
    "id": "brand-accbbc4e5d81fff0",
    "name": "WPS Office",
    "group": "办公与效率",
    "aliases": [
      "WPS Office"
    ]
  },
  {
    "id": "brand-73bcfe98830b53a1",
    "name": "Notion",
    "group": "办公与效率",
    "aliases": [
      "Notion"
    ]
  },
  {
    "id": "brand-7b836ff8388ef97c",
    "name": "Goodnotes",
    "group": "办公与效率",
    "aliases": [
      "Goodnotes"
    ]
  },
  {
    "id": "brand-915ef4bad59a1329",
    "name": "Google Drive",
    "group": "网盘与存储",
    "aliases": [
      "Google Drive"
    ]
  },
  {
    "id": "brand-4750d0a12e03a1be",
    "name": "Dropbox",
    "group": "网盘与存储",
    "aliases": [
      "Dropbox"
    ]
  },
  {
    "id": "brand-8a7a54d38f1a7e32",
    "name": "OneDrive",
    "group": "网盘与存储",
    "aliases": [
      "OneDrive"
    ]
  },
  {
    "id": "brand-b5eaa6e7444f6dd7",
    "name": "百度网盘",
    "group": "网盘与存储",
    "aliases": [
      "百度网盘"
    ]
  },
  {
    "id": "brand-e9665f54d274f44e",
    "name": "阿里云盘",
    "group": "网盘与存储",
    "aliases": [
      "阿里云盘"
    ]
  },
  {
    "id": "brand-d5291dd3ee13f829",
    "name": "夸克网盘",
    "group": "网盘与存储",
    "aliases": [
      "夸克网盘"
    ]
  },
  {
    "id": "brand-2f73335c712c9214",
    "name": "Canva",
    "group": "创作与设计",
    "aliases": [
      "Canva"
    ]
  },
  {
    "id": "brand-093c2597d7f28f73",
    "name": "CapCut",
    "group": "创作与设计",
    "aliases": [
      "CapCut"
    ]
  },
  {
    "id": "brand-1afc8bb18decc6dd",
    "name": "剪映",
    "group": "创作与设计",
    "aliases": []
  },
  {
    "id": "brand-60a648def576a07e",
    "name": "Lightroom",
    "group": "创作与设计",
    "aliases": [
      "Lightroom"
    ]
  },
  {
    "id": "brand-d1cd971aa6f69253",
    "name": "Adobe Express",
    "group": "创作与设计",
    "aliases": [
      "Adobe Express"
    ]
  },
  {
    "id": "brand-ce46041005a8aa0d",
    "name": "Figma",
    "group": "创作与设计",
    "aliases": [
      "Figma"
    ]
  },
  {
    "id": "brand-b48c1831a03feab8",
    "name": "Procreate Pocket",
    "group": "创作与设计",
    "aliases": [
      "Procreate Pocket"
    ]
  },
  {
    "id": "brand-e9aa6f761190f23c",
    "name": "Strava",
    "group": "健康、健身与运动",
    "aliases": [
      "Strava"
    ]
  },
  {
    "id": "brand-1e67b40f2d64665d",
    "name": "AllTrails",
    "group": "健康、健身与运动",
    "aliases": [
      "AllTrails"
    ]
  },
  {
    "id": "brand-183f00f483d3844e",
    "name": "Keep",
    "group": "健康、健身与运动",
    "aliases": []
  },
  {
    "id": "brand-e5879951eb998dab",
    "name": "MyFitnessPal",
    "group": "健康、健身与运动",
    "aliases": [
      "MyFitnessPal"
    ]
  },
  {
    "id": "brand-38f6b83e2dc175c7",
    "name": "Calm",
    "group": "健康、健身与运动",
    "aliases": []
  },
  {
    "id": "brand-8e9b845f943fc8b0",
    "name": "PureGym",
    "group": "健康、健身与运动",
    "aliases": [
      "PureGym"
    ]
  },
  {
    "id": "brand-a3651e8fe91621dd",
    "name": "24/7 Fitness",
    "group": "健康、健身与运动",
    "aliases": [
      "24/7 Fitness"
    ]
  },
  {
    "id": "brand-616aec2ec9eccc74",
    "name": "Planet Fitness",
    "group": "健康、健身与运动",
    "aliases": [
      "Planet Fitness"
    ]
  },
  {
    "id": "brand-be433280de3a4365",
    "name": "Costco",
    "group": "购物与会员",
    "aliases": [
      "Costco"
    ]
  },
  {
    "id": "brand-0f686f85f586c202",
    "name": "山姆会员商店",
    "group": "购物与会员",
    "aliases": [
      "山姆会员商店"
    ]
  },
  {
    "id": "brand-3eab285c90aa3223",
    "name": "Walmart",
    "group": "购物与会员",
    "aliases": [
      "Walmart"
    ]
  },
  {
    "id": "brand-81baf57e05f11276",
    "name": "京东",
    "group": "购物与会员",
    "aliases": []
  },
  {
    "id": "brand-da14d8f7500f7e61",
    "name": "淘宝",
    "group": "购物与会员",
    "aliases": []
  },
  {
    "id": "brand-fad070cff2ed8a64",
    "name": "Tesco",
    "group": "购物与会员",
    "aliases": [
      "Tesco"
    ]
  },
  {
    "id": "brand-effea4c9ff35497c",
    "name": "拼多多",
    "group": "购物与会员",
    "aliases": [
      "拼多多"
    ]
  },
  {
    "id": "brand-4150177b54900ee8",
    "name": "Starbucks",
    "group": "餐饮与外卖",
    "aliases": [
      "Starbucks"
    ]
  },
  {
    "id": "brand-268d99ac6debb8a0",
    "name": "瑞幸咖啡",
    "group": "餐饮与外卖",
    "aliases": [
      "瑞幸咖啡"
    ]
  },
  {
    "id": "brand-1081fdaaeceae9d9",
    "name": "McDonald's",
    "group": "餐饮与外卖",
    "aliases": [
      "McDonald's"
    ]
  },
  {
    "id": "brand-153091ce6e774499",
    "name": "DoorDash",
    "group": "餐饮与外卖",
    "aliases": [
      "DoorDash"
    ]
  },
  {
    "id": "brand-31263a45e794c7a4",
    "name": "Keeta",
    "group": "餐饮与外卖",
    "aliases": [
      "Keeta"
    ]
  },
  {
    "id": "brand-cd6362472aea60ef",
    "name": "美团",
    "group": "餐饮与外卖",
    "aliases": []
  },
  {
    "id": "brand-3cfbdbc3ba7620f9",
    "name": "Uber",
    "group": "旅行与交通",
    "aliases": [
      "Uber"
    ]
  },
  {
    "id": "brand-571ce0217afc888b",
    "name": "Lyft",
    "group": "旅行与交通",
    "aliases": [
      "Lyft"
    ]
  },
  {
    "id": "brand-1d927621f5321e99",
    "name": "Airbnb",
    "group": "旅行与交通",
    "aliases": [
      "Airbnb"
    ]
  },
  {
    "id": "brand-04a109180efc63cb",
    "name": "Trip.com",
    "group": "旅行与交通",
    "aliases": [
      "Trip.com"
    ]
  },
  {
    "id": "brand-49233b820253f8ef",
    "name": "携程",
    "group": "旅行与交通",
    "aliases": []
  },
  {
    "id": "brand-57b33bc4f2a1d871",
    "name": "滴滴",
    "group": "旅行与交通",
    "aliases": []
  },
  {
    "id": "brand-741765d017c050cf",
    "name": "Trainline",
    "group": "旅行与交通",
    "aliases": [
      "Trainline"
    ]
  },
  {
    "id": "brand-fc7b67fc71014fff",
    "name": "MTR Mobile",
    "group": "旅行与交通",
    "aliases": [
      "MTR Mobile"
    ]
  },
  {
    "id": "brand-2923740fe800e250",
    "name": "Google Maps",
    "group": "导航",
    "aliases": [
      "Google Maps"
    ]
  },
  {
    "id": "brand-1ecb3ba10a167e3c",
    "name": "高德地图",
    "group": "导航",
    "aliases": [
      "高德地图"
    ]
  },
  {
    "id": "brand-302415affc9a5568",
    "name": "Waze",
    "group": "导航",
    "aliases": [
      "Waze"
    ]
  },
  {
    "id": "brand-aa7899c7c392113a",
    "name": "Citymapper",
    "group": "导航",
    "aliases": [
      "Citymapper"
    ]
  },
  {
    "id": "brand-0453b8f9e9b20902",
    "name": "Duolingo",
    "group": "教育与参考",
    "aliases": [
      "Duolingo"
    ]
  },
  {
    "id": "brand-343856a7c4d78fa0",
    "name": "Google Classroom",
    "group": "教育与参考",
    "aliases": [
      "Google Classroom"
    ]
  },
  {
    "id": "brand-3c1f52eeebdc4db1",
    "name": "有道词典",
    "group": "教育与参考",
    "aliases": [
      "有道词典"
    ]
  },
  {
    "id": "brand-47a414e6183a3751",
    "name": "Google Translate",
    "group": "教育与参考",
    "aliases": [
      "Google Translate"
    ]
  },
  {
    "id": "brand-b1bc56450f0bc098",
    "name": "Kindle",
    "group": "阅读与有声书",
    "aliases": [
      "Kindle"
    ]
  },
  {
    "id": "brand-92b4440b37d35124",
    "name": "Audible",
    "group": "阅读与有声书",
    "aliases": [
      "Audible"
    ]
  },
  {
    "id": "brand-987dccf2ea2b28cc",
    "name": "微信读书",
    "group": "阅读与有声书",
    "aliases": [
      "微信读书"
    ]
  },
  {
    "id": "brand-ae322cc596675baf",
    "name": "喜马拉雅",
    "group": "阅读与有声书",
    "aliases": [
      "喜马拉雅"
    ]
  },
  {
    "id": "brand-8b970e423d67e179",
    "name": "Kobo",
    "group": "阅读与有声书",
    "aliases": [
      "Kobo"
    ]
  },
  {
    "id": "brand-cef48094c18a91b3",
    "name": "The New York Times",
    "group": "新闻与报刊订阅",
    "aliases": [
      "The New York Times"
    ]
  },
  {
    "id": "brand-3475ef3028c08f26",
    "name": "The Wall Street Journal",
    "group": "新闻与报刊订阅",
    "aliases": [
      "The Wall Street Journal"
    ]
  },
  {
    "id": "brand-e5c07c1fdd938261",
    "name": "The Times",
    "group": "新闻与报刊订阅",
    "aliases": [
      "The Times"
    ]
  },
  {
    "id": "brand-d34fd66d3ef962bb",
    "name": "The Telegraph",
    "group": "新闻与报刊订阅",
    "aliases": [
      "The Telegraph"
    ]
  },
  {
    "id": "brand-d44f5b3e24a6da0d",
    "name": "South China Morning Post",
    "group": "新闻与报刊订阅",
    "aliases": [
      "South China Morning Post"
    ]
  },
  {
    "id": "brand-8c339ec81c3ea691",
    "name": "Substack",
    "group": "新闻与报刊订阅",
    "aliases": [
      "Substack"
    ]
  },
  {
    "id": "brand-3ed3fdfdbbc9f018",
    "name": "香港01",
    "group": "新闻与报刊订阅",
    "aliases": [
      "香港01"
    ]
  },
  {
    "id": "brand-81b430b696435180",
    "name": "微信",
    "group": "通讯、社交与安全",
    "aliases": []
  },
  {
    "id": "brand-2f04a3aa051f1f60",
    "name": "QQ",
    "group": "通讯、社交与安全",
    "aliases": []
  },
  {
    "id": "brand-acdd1e734125f341",
    "name": "Telegram",
    "group": "通讯、社交与安全",
    "aliases": [
      "Telegram"
    ]
  },
  {
    "id": "brand-053bc65874ad6098",
    "name": "Discord",
    "group": "通讯、社交与安全",
    "aliases": [
      "Discord"
    ]
  },
  {
    "id": "brand-dd84425b72da12c6",
    "name": "LinkedIn",
    "group": "通讯、社交与安全",
    "aliases": [
      "LinkedIn"
    ]
  },
  {
    "id": "brand-ac7606ebfd021341",
    "name": "NordVPN",
    "group": "通讯、社交与安全",
    "aliases": [
      "NordVPN"
    ]
  },
  {
    "id": "brand-8d10b64d749d7e27",
    "name": "ExpressVPN",
    "group": "通讯、社交与安全",
    "aliases": [
      "ExpressVPN"
    ]
  },
  {
    "id": "brand-cbbea9d808ebfe70",
    "name": "Surfshark",
    "group": "通讯、社交与安全",
    "aliases": [
      "Surfshark"
    ]
  },
  {
    "id": "brand-8d0fc70cea9187c6",
    "name": "中国移动",
    "group": "中国大陆手机运营商",
    "aliases": [
      "中国移动"
    ]
  },
  {
    "id": "brand-7b88db3210925677",
    "name": "中国联通",
    "group": "中国大陆手机运营商",
    "aliases": [
      "中国联通"
    ]
  },
  {
    "id": "brand-0684c4f2a2f949a3",
    "name": "中国电信",
    "group": "中国大陆手机运营商",
    "aliases": [
      "中国电信"
    ]
  },
  {
    "id": "brand-f911e414cf6bdfc5",
    "name": "GitHub",
    "group": "开发工具",
    "aliases": [
      "GitHub"
    ]
  },
  {
    "id": "brand-601a29658a2d36c4",
    "name": "Replit",
    "group": "开发工具",
    "aliases": [
      "Replit"
    ]
  },
  {
    "id": "brand-6453a64fc695d701",
    "name": "Windy.com",
    "group": "天气",
    "aliases": [
      "Windy.com"
    ]
  },
  {
    "id": "brand-b83ec2d41f6fcc75",
    "name": "AccuWeather",
    "group": "天气",
    "aliases": [
      "AccuWeather"
    ]
  },
  {
    "id": "brand-c5b1c5d04a058c3f",
    "name": "彩云天气",
    "group": "天气",
    "aliases": [
      "彩云天气"
    ]
  },
  {
    "id": "brand-33b47af199c327fc",
    "name": "MyObservatory",
    "group": "天气",
    "aliases": [
      "MyObservatory"
    ]
  },
  {
    "id": "brand-934ee512583692b2",
    "name": "CVS Health",
    "group": "医疗与生活服务",
    "aliases": [
      "CVS Health"
    ]
  },
  {
    "id": "brand-2837e282166f3c5d",
    "name": "MyChart",
    "group": "医疗与生活服务",
    "aliases": [
      "MyChart"
    ]
  },
  {
    "id": "brand-f3d8869ce3625d21",
    "name": "HA Go",
    "group": "医疗与生活服务",
    "aliases": [
      "HA Go"
    ]
  },
  {
    "id": "brand-7e0d951b2b392798",
    "name": "NHS App",
    "group": "医疗与生活服务",
    "aliases": [
      "NHS App"
    ]
  },
  {
    "id": "brand-17c0481b40d09071",
    "name": "王者荣耀",
    "group": "游戏",
    "aliases": [
      "王者荣耀"
    ]
  },
  {
    "id": "brand-47358d382f26024e",
    "name": "和平精英",
    "group": "游戏",
    "aliases": [
      "和平精英"
    ]
  },
  {
    "id": "brand-6c08dd9110071630",
    "name": "RedotPay",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "RedotPay"
    ]
  },
  {
    "id": "brand-181187ba991ba4b4",
    "name": "Bybit Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Bybit Card"
    ]
  },
  {
    "id": "brand-107242d376b660d8",
    "name": "Crypto.com Prepaid Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Crypto.com Prepaid Card"
    ]
  },
  {
    "id": "brand-8295deb98137d4e8",
    "name": "Wirex",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Wirex"
    ]
  },
  {
    "id": "brand-4c083db1c283fec1",
    "name": "Nexo Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Nexo Card"
    ]
  },
  {
    "id": "brand-0370a62b904e4b47",
    "name": "OKX Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "OKX Card"
    ]
  },
  {
    "id": "brand-5038cd91fa8fbc26",
    "name": "Bitget Wallet Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Bitget Wallet Card"
    ]
  },
  {
    "id": "brand-04127553b4fb06d0",
    "name": "SafePal / Fiat24",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "SafePal"
    ]
  },
  {
    "id": "brand-5d95dad8e25d6e3a",
    "name": "TokenPocket TP Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "TokenPocket TP Card"
    ]
  },
  {
    "id": "brand-9b1e6040c2d209ea",
    "name": "Pionex Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "Pionex Card"
    ]
  },
  {
    "id": "brand-6ed8e486de8bb03b",
    "name": "ether.fi Cash",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "ether.fi Cash"
    ]
  },
  {
    "id": "brand-5262111f33e05963",
    "name": "MetaMask Card",
    "group": "U卡／加密货币支付卡",
    "aliases": [
      "MetaMask Card"
    ]
  },
  {
    "id": "brand-854377eb28f08346",
    "name": "中国广电",
    "group": "中国大陆手机运营商",
    "aliases": [
      "中国广电"
    ]
  },
  {
    "id": "brand-d1aff162effb746e",
    "name": "AT&T",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "AT&T"
    ]
  },
  {
    "id": "brand-bd3cba85ce4cde43",
    "name": "Verizon",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Verizon"
    ]
  },
  {
    "id": "brand-66bd51ee0dbc4bca",
    "name": "T-Mobile",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "T-Mobile"
    ]
  },
  {
    "id": "brand-7085b91e3c52f69a",
    "name": "Mint Mobile",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Mint Mobile"
    ]
  },
  {
    "id": "brand-02d927a049a259ac",
    "name": "Metro by T-Mobile",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Metro by T-Mobile"
    ]
  },
  {
    "id": "brand-f2b81d85a1003c1d",
    "name": "Ultra Mobile",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Ultra Mobile"
    ]
  },
  {
    "id": "brand-8411f5abb4c710b1",
    "name": "Visible",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Visible"
    ]
  },
  {
    "id": "brand-3100f9d1060c22d0",
    "name": "Total Wireless",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Total Wireless"
    ]
  },
  {
    "id": "brand-295c12597b1739a6",
    "name": "Cricket Wireless",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Cricket Wireless"
    ]
  },
  {
    "id": "brand-b2039dc0b9fafb38",
    "name": "Google Fi Wireless",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "Google Fi Wireless"
    ]
  },
  {
    "id": "brand-42f3ac682ece1164",
    "name": "US Mobile",
    "group": "美国手机运营商与消费品牌",
    "aliases": [
      "US Mobile"
    ]
  },
  {
    "id": "brand-8d38d3b6233f4781",
    "name": "中国移动香港／CMHK",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "中国移动香港",
      "CMHK"
    ]
  },
  {
    "id": "brand-56e1a0723f1d4616",
    "name": "csl.",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "csl."
    ]
  },
  {
    "id": "brand-2f27954b79f6b3c0",
    "name": "1O1O",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "1O1O"
    ]
  },
  {
    "id": "brand-5a602d15a5820f43",
    "name": "3 Hong Kong",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "3 Hong Kong"
    ]
  },
  {
    "id": "brand-3fc7e6c97a6988e4",
    "name": "SmarTone／数码通",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "SmarTone",
      "数码通"
    ]
  },
  {
    "id": "brand-79ae270ddf6eb1bd",
    "name": "Birdie／自由鸟",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "Birdie",
      "自由鸟"
    ]
  },
  {
    "id": "brand-d044fac5b926e628",
    "name": "SoSIM",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "SoSIM"
    ]
  },
  {
    "id": "brand-0e65394d692a2f12",
    "name": "Club SIM",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "Club SIM"
    ]
  },
  {
    "id": "brand-e89345d940a42dc0",
    "name": "SUN Mobile",
    "group": "香港手机运营商与消费品牌",
    "aliases": [
      "SUN Mobile"
    ]
  },
  {
    "id": "brand-bd43c62d6ccc0ceb",
    "name": "EE",
    "group": "英国手机运营商与消费品牌",
    "aliases": []
  },
  {
    "id": "brand-69ccf59b416bc5b3",
    "name": "O2",
    "group": "英国手机运营商与消费品牌",
    "aliases": []
  },
  {
    "id": "brand-2e34fd6e4ef1a5d0",
    "name": "Vodafone UK",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Vodafone UK"
    ]
  },
  {
    "id": "brand-37d401bc53ab48d6",
    "name": "Three UK",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Three UK"
    ]
  },
  {
    "id": "brand-fd1696acc61502c7",
    "name": "giffgaff",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "giffgaff"
    ]
  },
  {
    "id": "brand-fe96a898b529366a",
    "name": "Tesco Mobile",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Tesco Mobile"
    ]
  },
  {
    "id": "brand-05636ecd7a0644d4",
    "name": "Sky Mobile",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Sky Mobile"
    ]
  },
  {
    "id": "brand-2543d920c5347ebb",
    "name": "VOXI",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "VOXI"
    ]
  },
  {
    "id": "brand-d05f6c8853d7fa56",
    "name": "SMARTY",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "SMARTY"
    ]
  },
  {
    "id": "brand-2c75c5f6caa8803c",
    "name": "iD Mobile",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "iD Mobile"
    ]
  },
  {
    "id": "brand-938600840aedcf57",
    "name": "Lebara UK",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Lebara UK"
    ]
  },
  {
    "id": "brand-2b1bbe44e8af51d5",
    "name": "Lycamobile UK",
    "group": "英国手机运营商与消费品牌",
    "aliases": [
      "Lycamobile UK"
    ]
  },
  {
    "id": "brand-7f073d54aeb1453a",
    "name": "Tesla／特斯拉",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Tesla",
      "特斯拉"
    ]
  },
  {
    "id": "brand-54a84b779870febc",
    "name": "Volkswagen／大众",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Volkswagen"
    ]
  },
  {
    "id": "brand-1fe317a3930a0a22",
    "name": "Audi／奥迪",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Audi"
    ]
  },
  {
    "id": "brand-a90a235139403c74",
    "name": "Porsche／保时捷",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Porsche",
      "保时捷"
    ]
  },
  {
    "id": "brand-14f963cdebc312f4",
    "name": "Škoda／斯柯达",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Škoda",
      "斯柯达"
    ]
  },
  {
    "id": "brand-8f5db3682475080c",
    "name": "CUPRA",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "CUPRA"
    ]
  },
  {
    "id": "brand-eb199c582b380999",
    "name": "BMW／宝马",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "BMW"
    ]
  },
  {
    "id": "brand-8ddefb0087b1484e",
    "name": "MINI",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": []
  },
  {
    "id": "brand-7146bb9bfe2cc937",
    "name": "Mercedes-Benz／奔驰",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Mercedes-Benz"
    ]
  },
  {
    "id": "brand-b62d50d64dd85fef",
    "name": "Volvo／沃尔沃",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Volvo",
      "沃尔沃"
    ]
  },
  {
    "id": "brand-16887cb78fee70e6",
    "name": "Land Rover／路虎",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Land Rover"
    ]
  },
  {
    "id": "brand-4beac98d6b970184",
    "name": "Jaguar／捷豹",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Jaguar"
    ]
  },
  {
    "id": "brand-3b7867056fbe15ef",
    "name": "Peugeot／标致",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Peugeot"
    ]
  },
  {
    "id": "brand-25ca826790387ee1",
    "name": "Citroën／雪铁龙",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Citroën",
      "雪铁龙"
    ]
  },
  {
    "id": "brand-2617ad5916dfd467",
    "name": "Vauxhall",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Vauxhall"
    ]
  },
  {
    "id": "brand-cdb435a9080fa7f5",
    "name": "Renault／雷诺",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Renault"
    ]
  },
  {
    "id": "brand-3e94c1e85f8c8484",
    "name": "Fiat／菲亚特",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Fiat",
      "菲亚特"
    ]
  },
  {
    "id": "brand-e98a013e5e2e395d",
    "name": "Jeep",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Jeep"
    ]
  },
  {
    "id": "brand-b2d4516e41c0e2a3",
    "name": "Ford／福特",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Ford"
    ]
  },
  {
    "id": "brand-fea67f0ffe22d188",
    "name": "Lincoln／林肯",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Lincoln"
    ]
  },
  {
    "id": "brand-1e612ddc8a331a49",
    "name": "Chevrolet／雪佛兰",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Chevrolet",
      "雪佛兰"
    ]
  },
  {
    "id": "brand-bc89b6dc4d866186",
    "name": "Buick／别克",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Buick"
    ]
  },
  {
    "id": "brand-c5f36f3aadd42d15",
    "name": "Cadillac／凯迪拉克",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Cadillac",
      "凯迪拉克"
    ]
  },
  {
    "id": "brand-a4ad4d4d6635467d",
    "name": "GMC",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "GMC"
    ]
  },
  {
    "id": "brand-4f241cd4f73aecc5",
    "name": "Toyota／丰田",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Toyota"
    ]
  },
  {
    "id": "brand-56f0d73541e82c3f",
    "name": "Lexus／雷克萨斯",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Lexus",
      "雷克萨斯"
    ]
  },
  {
    "id": "brand-133a62a291400c7c",
    "name": "Honda／本田",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Honda"
    ]
  },
  {
    "id": "brand-5184c5ccab1a6c6f",
    "name": "Nissan／日产",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Nissan"
    ]
  },
  {
    "id": "brand-e3e0f227975425a5",
    "name": "Mazda／马自达",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Mazda",
      "马自达"
    ]
  },
  {
    "id": "brand-2683a2acfc9299dd",
    "name": "Subaru／斯巴鲁",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Subaru",
      "斯巴鲁"
    ]
  },
  {
    "id": "brand-2dc2b7b140424040",
    "name": "Hyundai／现代",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Hyundai"
    ]
  },
  {
    "id": "brand-3ee386b0fe612350",
    "name": "Kia／起亚",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Kia"
    ]
  },
  {
    "id": "brand-19b8a3e7741676b0",
    "name": "Genesis／捷尼赛思",
    "group": "汽车品牌：国际与欧美日系",
    "aliases": [
      "Genesis",
      "捷尼赛思"
    ]
  },
  {
    "id": "brand-480ac83de932e557",
    "name": "BYD／比亚迪",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "BYD",
      "比亚迪"
    ]
  },
  {
    "id": "brand-eed88ae172047e11",
    "name": "Geely／吉利",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "Geely"
    ]
  },
  {
    "id": "brand-1ba52ccc50f72660",
    "name": "Lynk & Co／领克",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "Lynk & Co"
    ]
  },
  {
    "id": "brand-62ac52ca4dc4caa8",
    "name": "Zeekr／极氪",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "Zeekr"
    ]
  },
  {
    "id": "brand-a3c4266d9345f11f",
    "name": "NIO／蔚来",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "NIO"
    ]
  },
  {
    "id": "brand-019d5d6f23bf9446",
    "name": "XPeng／小鹏",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "XPeng"
    ]
  },
  {
    "id": "brand-d3c20bd565303d39",
    "name": "理想汽车",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "理想汽车"
    ]
  },
  {
    "id": "brand-96ea8fc8b10f3a01",
    "name": "小米汽车",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "小米汽车"
    ]
  },
  {
    "id": "brand-34c667101c639044",
    "name": "AITO／问界",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "AITO"
    ]
  },
  {
    "id": "brand-7117fa8d72fb99b9",
    "name": "长安汽车",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "长安汽车"
    ]
  },
  {
    "id": "brand-b76d5350028dfa74",
    "name": "深蓝汽车",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "深蓝汽车"
    ]
  },
  {
    "id": "brand-7b56d9ac5b8f2477",
    "name": "AVATR／阿维塔",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "AVATR",
      "阿维塔"
    ]
  },
  {
    "id": "brand-9aff75ca94b86763",
    "name": "Chery／奇瑞",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "Chery"
    ]
  },
  {
    "id": "brand-1403a55e2eeebf16",
    "name": "HAVAL／哈弗",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "HAVAL"
    ]
  },
  {
    "id": "brand-afc476e0e32e6909",
    "name": "TANK／坦克",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "TANK"
    ]
  },
  {
    "id": "brand-c92ea5ccbde2fe28",
    "name": "AION／埃安",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "AION"
    ]
  },
  {
    "id": "brand-b25d4954af714fbc",
    "name": "Leapmotor／零跑",
    "group": "汽车品牌：中国品牌",
    "aliases": [
      "Leapmotor"
    ]
  },
  {
    "id": "brand-47baf3a38c274d70",
    "name": "Apple One",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple One"
    ]
  },
  {
    "id": "brand-dcb1448b6d5bef08",
    "name": "iCloud+",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "iCloud+"
    ]
  },
  {
    "id": "brand-3b00b32d64af3c23",
    "name": "Apple Music",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple Music"
    ]
  },
  {
    "id": "brand-e621165ce13e0ef5",
    "name": "Apple TV（订阅服务）",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple TV（订阅服务）"
    ]
  },
  {
    "id": "brand-c642fdf45b2882bc",
    "name": "Apple Arcade",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple Arcade"
    ]
  },
  {
    "id": "brand-7c3f048af591b972",
    "name": "Apple Fitness+",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple Fitness+"
    ]
  },
  {
    "id": "brand-da3a2406bd90809a",
    "name": "Apple News+",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Apple News+"
    ]
  },
  {
    "id": "brand-d1cac591c672f912",
    "name": "Amazon Prime",
    "group": "订阅补充：Apple 与综合套装",
    "aliases": [
      "Amazon Prime"
    ]
  },
  {
    "id": "brand-d8d384c4e02cb94e",
    "name": "YouTube Premium",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "YouTube Premium"
    ]
  },
  {
    "id": "brand-4997d093758bf1ad",
    "name": "Deezer",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "Deezer"
    ]
  },
  {
    "id": "brand-6ba934928aa14ad5",
    "name": "DAZN",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "DAZN"
    ]
  },
  {
    "id": "brand-392b3b34d7f49ebb",
    "name": "NOW（英国）",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "NOW（英国）"
    ]
  },
  {
    "id": "brand-785ba7c5543bf611",
    "name": "Now TV（香港）",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "Now TV（香港）"
    ]
  },
  {
    "id": "brand-a014c1c4bf844591",
    "name": "Crunchyroll",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "Crunchyroll"
    ]
  },
  {
    "id": "brand-12841e813fb9e429",
    "name": "myTV SUPER",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "myTV SUPER"
    ]
  },
  {
    "id": "brand-6ee83476fe7d41d0",
    "name": "Viu",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "Viu"
    ]
  },
  {
    "id": "brand-7df999bb5bbab0b3",
    "name": "芒果TV",
    "group": "订阅补充：影音与体育",
    "aliases": [
      "芒果TV"
    ]
  },
  {
    "id": "brand-2e4b5921ffde84c2",
    "name": "Google One",
    "group": "订阅补充：办公、云存储与设计",
    "aliases": [
      "Google One"
    ]
  },
  {
    "id": "brand-8e9c94329ae8b1a6",
    "name": "Microsoft 365",
    "group": "订阅补充：办公、云存储与设计",
    "aliases": [
      "Microsoft 365"
    ]
  },
  {
    "id": "brand-02e75c98a053e228",
    "name": "Adobe Creative Cloud",
    "group": "订阅补充：办公、云存储与设计",
    "aliases": [
      "Adobe Creative Cloud"
    ]
  },
  {
    "id": "brand-764d4c6d3e32933a",
    "name": "Todoist",
    "group": "订阅补充：办公、云存储与设计",
    "aliases": [
      "Todoist"
    ]
  },
  {
    "id": "brand-bc031f81734b4d02",
    "name": "Setapp",
    "group": "订阅补充：办公、云存储与设计",
    "aliases": [
      "Setapp"
    ]
  },
  {
    "id": "brand-4a9e4a5e58be4df9",
    "name": "1Password",
    "group": "订阅补充：密码与隐私",
    "aliases": [
      "1Password"
    ]
  },
  {
    "id": "brand-fb54e0f95e21a991",
    "name": "Bitwarden",
    "group": "订阅补充：密码与隐私",
    "aliases": [
      "Bitwarden"
    ]
  },
  {
    "id": "brand-f7b39b2d1a2a93b8",
    "name": "Proton",
    "group": "订阅补充：密码与隐私",
    "aliases": [
      "Proton"
    ]
  },
  {
    "id": "brand-61e19208df06395c",
    "name": "PlayStation Plus",
    "group": "订阅补充：游戏会员与云游戏",
    "aliases": [
      "PlayStation Plus"
    ]
  },
  {
    "id": "brand-df2f91012c221bc2",
    "name": "Xbox Game Pass",
    "group": "订阅补充：游戏会员与云游戏",
    "aliases": [
      "Xbox Game Pass"
    ]
  },
  {
    "id": "brand-39d2409ac58a1a63",
    "name": "Nintendo Switch Online",
    "group": "订阅补充：游戏会员与云游戏",
    "aliases": [
      "Nintendo Switch Online"
    ]
  },
  {
    "id": "brand-81f5470f1e04014b",
    "name": "GeForce NOW",
    "group": "订阅补充：游戏会员与云游戏",
    "aliases": [
      "GeForce NOW"
    ]
  },
  {
    "id": "brand-9b1a14126585226c",
    "name": "Coursera Plus",
    "group": "订阅补充：学习、健身与冥想",
    "aliases": [
      "Coursera Plus"
    ]
  },
  {
    "id": "brand-e8c0eab4994ba898",
    "name": "MasterClass",
    "group": "订阅补充：学习、健身与冥想",
    "aliases": [
      "MasterClass"
    ]
  },
  {
    "id": "brand-d42c2d80abf827fe",
    "name": "Skillshare",
    "group": "订阅补充：学习、健身与冥想",
    "aliases": [
      "Skillshare"
    ]
  },
  {
    "id": "brand-a6bbbb95cddbd970",
    "name": "Headspace",
    "group": "订阅补充：学习、健身与冥想",
    "aliases": [
      "Headspace"
    ]
  },
  {
    "id": "brand-ff98d8a1e29266f6",
    "name": "Peloton",
    "group": "订阅补充：学习、健身与冥想",
    "aliases": [
      "Peloton"
    ]
  },
  {
    "id": "brand-492cae23f6e556f3",
    "name": "JetBrains",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "JetBrains"
    ]
  },
  {
    "id": "brand-f9191531404c4016",
    "name": "Cloudflare",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "Cloudflare"
    ]
  },
  {
    "id": "brand-68edc75c015e2e10",
    "name": "Vercel",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "Vercel"
    ]
  },
  {
    "id": "brand-8db02fc979fdbbb6",
    "name": "DigitalOcean",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "DigitalOcean"
    ]
  },
  {
    "id": "brand-e16fc821f34228d1",
    "name": "阿里云",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "阿里云"
    ]
  },
  {
    "id": "brand-a7baed72c308ce88",
    "name": "腾讯云",
    "group": "订阅补充：开发工具、托管与续费账单",
    "aliases": [
      "腾讯云"
    ]
  }
]
